"""Городские страницы сайта A «МираМе» — теплый тон с легким юмором (ТЗ 9.1).

Каждый текст написан для своего города. Адреса и координаты не заполнены: владелец вносит
реальные данные в админке («Города — страницы»), после этого на странице появляется карта.
"""

PAGE = {
    "kind": "cities", "slug_ru": "города", "slug_en": "cities",
    "title_ru": "Картины в вашем городе", "title_en": "Paintings in your city",
    "nav_title_ru": "Города", "nav_title_en": "Cities",
    "kicker_ru": "География", "kicker_en": "Geography",
    "intro_ru": "Картине не обязательно жить там, где ее написали. Выберите свой город — расскажем, как она к вам доберется, и покажем работы, которые уже ждут знакомства.",
    "intro_en": "A painting doesn’t have to live where it was painted. Choose your city — we’ll tell you how it gets to you and show the works waiting to meet you.",
    "empty_ru": "Городские страницы скоро появятся. А пока просто напишите, куда нужна картина.",
    "empty_en": "City pages are coming soon. Meanwhile, just tell us where the painting should go.",
    "cta_text_ru": "Вашего города нет в списке? Картина все равно доедет", "cta_text_en": "Your city isn’t listed? The painting will still get there",
    "cta_button_ru": "Обсудить доставку", "cta_button_en": "Discuss delivery",
    "seo_title_ru": "Картины с доставкой по городам России", "seo_title_en": "Paintings delivered across Russia",
    "seo_description_ru": "Картины в наличии и на заказ с доставкой в Москву, Санкт-Петербург, Новосибирск и другие города. Выберите свой город и узнайте, как картина к вам доберется.",
    "seo_description_en": "Paintings in stock and made to order, delivered to Moscow, Saint Petersburg, Novosibirsk and other cities. Choose your city and see how the painting gets to you.",
}

DELIVERY_RU = "Отправляем {to} через СДЭК или другую транспортную компанию по согласованию с вами. Забрать картину можно в пункте выдачи или заказать курьера. Стоимость доставки оплачивается отдельно; упаковку, маршрут и срок уточним до отправки."
DELIVERY_EN = "We ship to {name} via CDEK or another carrier agreed with you. You can collect the painting at a pick-up point or order a courier. Delivery is paid separately; packing, route and timing are agreed before shipping."

CITIES = [
    {"source_id": "524901", "name_ru": "Москва", "name_en": "Moscow", "name_in_ru": "в Москве", "to": "в Москву",
     "title_ru": "Картины в Москве: в наличии и на заказ", "title_en": "Paintings in Moscow: in stock and made to order",
     "intro_ru": "В Москве найдется стена для чего угодно — от спокойного моря до смелой абстракции. Осталось выбрать, что будет на ней жить.",
     "intro_en": "In Moscow there is a wall for anything — from a calm sea to bold abstraction. All that’s left is to choose what lives on it.",
     "body_ru": "Московские квартиры бывают очень разными: высокие потолки сталинок, компактные новостройки, лофты с кирпичом. Под каждую подходит свой формат — вытянутая панорама над диваном, пара квадратов в прихожей или одна большая работа, которая сразу задает настроение.\n\nЕсли город за окном шумный и быстрый, дома хочется тишины: морского горизонта, мягких цветов, неторопливого пейзажа. А если хочется, наоборот, энергии — абстракция справится не хуже утреннего кофе. Пришлите фото стены — подскажем размер и сюжет.",
     "body_en": "Moscow flats are very different: tall Stalin-era ceilings, compact new builds, brick lofts. Each suits its own format — a long panorama above the sofa, a pair of squares in the hallway or one large work that sets the mood.\n\nWhen the city outside is loud and fast, home wants calm: a sea horizon, soft flowers, an unhurried landscape. Send us a photo of the wall — we’ll suggest a size and subject.",
     "seo_title_ru": "Картины в Москве — в наличии и на заказ", "seo_title_en": "Paintings in Moscow",
     "seo_description_ru": "Картины для дома в Москве: готовые работы и картины на заказ. Подберем размер под вашу стену, доставим через СДЭК или другую ТК по согласованию."},
    {"source_id": "498817", "name_ru": "Санкт-Петербург", "name_en": "Saint Petersburg", "name_in_ru": "в Санкт-Петербурге", "to": "в Санкт-Петербург",
     "title_ru": "Картины в Санкт-Петербурге", "title_en": "Paintings in Saint Petersburg",
     "intro_ru": "Петербургский свет мягкий и переменчивый — картины здесь тоже любят, когда их рассматривают не спеша.",
     "intro_en": "Petersburg light is soft and changeable — paintings here like to be looked at slowly, too.",
     "body_ru": "В старом фонде с высокими потолками большая картина чувствует себя как дома, а в новых кварталах у залива хорошо смотрятся светлые морские сюжеты. Белые ночи и серые дни одинаково любят теплые оттенки: немного солнца на стене никогда не помешает.\n\nНева, мосты, дворы-колодцы — городскую тему в Петербурге можно продолжать бесконечно. А можно сделать наоборот и повесить дома то, чего за окном нет: цветущий сад или южное море.",
     "body_en": "In old buildings with high ceilings a large painting feels at home, while bright sea subjects look good in the new districts by the gulf. White nights and grey days both love warm tones — a little sunshine on the wall never hurts.\n\nOr do the opposite and hang what isn’t outside the window: a blooming garden or a southern sea.",
     "seo_title_ru": "Картины в Санкт-Петербурге", "seo_title_en": "Paintings in Saint Petersburg",
     "seo_description_ru": "Картины в наличии и на заказ с доставкой в Санкт-Петербург. Морские сюжеты, цветы, абстракция и городские виды — подберем формат под ваш интерьер."},
    {"source_id": "1496747", "name_ru": "Новосибирск", "name_en": "Novosibirsk", "name_in_ru": "в Новосибирске", "to": "в Новосибирск",
     "title_ru": "Картины в Новосибирске", "title_en": "Paintings in Novosibirsk",
     "intro_ru": "Сибирская зима длинная, а значит, у картины на стене будет много времени, чтобы радовать.",
     "intro_en": "The Siberian winter is long, which gives a painting on the wall plenty of time to please.",
     "body_ru": "Когда за окном снег лежит с ноября по апрель, дома особенно хочется цвета: сочной зелени, теплого заката, летнего поля. Картина здесь работает как маленькое окно в другое время года — без визы и чемодана.\n\nОбь, Академгородок, сосновые леса вокруг — любителям пейзажа есть откуда черпать вдохновение. Расскажите, что вам ближе, и мы подберем готовую работу или обсудим новую.",
     "body_en": "When snow lies outside from November to April, home especially wants colour: lush green, a warm sunset, a summer field. A painting here works like a small window into another season — no visa or suitcase needed.\n\nTell us what you like, and we’ll find a ready work or discuss a new one.",
     "seo_title_ru": "Картины в Новосибирске", "seo_title_en": "Paintings in Novosibirsk",
     "seo_description_ru": "Картины для дома в Новосибирске: готовые работы и картины на заказ. Яркие сюжеты для длинной зимы, доставка через СДЭК или другую ТК."},
    {"source_id": "1486209", "name_ru": "Екатеринбург", "name_en": "Yekaterinburg", "name_in_ru": "в Екатеринбурге", "to": "в Екатеринбург",
     "title_ru": "Картины в Екатеринбурге", "title_en": "Paintings in Yekaterinburg",
     "intro_ru": "Город на границе Европы и Азии умеет сочетать несочетаемое. Интерьер — тоже.",
     "intro_en": "A city on the border of Europe and Asia knows how to combine the uncombinable. So does an interior.",
     "body_ru": "Конструктивизм, стеклянные башни и уютные старые улицы рядом — в Екатеринбурге привыкли к контрастам. Поэтому здесь хорошо смотрятся и строгая графичная абстракция, и живой уральский пейзаж с лесом и камнем.\n\nЕсли не можете выбрать между «спокойно» и «смело», начните с места: где будет висеть картина и что вы хотите чувствовать, глядя на нее. Дальше разберемся вместе.",
     "body_en": "Constructivism, glass towers and cosy old streets side by side — Yekaterinburg is used to contrasts. Strict graphic abstraction and a lively Ural landscape both look good here.\n\nIf you can’t choose between calm and bold, start with the place: where the painting will hang and how you want to feel looking at it.",
     "seo_title_ru": "Картины в Екатеринбурге", "seo_title_en": "Paintings in Yekaterinburg",
     "seo_description_ru": "Картины в наличии и на заказ с доставкой в Екатеринбург. Абстракция, пейзажи и другие сюжеты — поможем выбрать работу для вашего интерьера."},
    {"source_id": "551487", "name_ru": "Казань", "name_en": "Kazan", "name_in_ru": "в Казани", "to": "в Казань",
     "title_ru": "Картины в Казани", "title_en": "Paintings in Kazan",
     "intro_ru": "Казань стоит там, где встречаются Волга и Казанка, — и картинам с водой здесь всегда рады.",
     "intro_en": "Kazan stands where the Volga meets the Kazanka — and paintings with water are always welcome here.",
     "body_ru": "В Казани рядом живут разные традиции, и интерьеры здесь часто такие же: восточный орнамент по соседству со скандинавской простотой. Картина может стать тем самым мостиком между ними — через цвет, узор или сюжет.\n\nЛюбите широкие речные просторы — посмотрите пейзажи и море. Хотите ярких акцентов — загляните в абстракцию и цветы. Сомневаетесь — пришлите фото комнаты, это лучше тысячи описаний.",
     "body_en": "Different traditions live side by side in Kazan, and interiors often do too: oriental ornament next to Scandinavian simplicity. A painting can be the bridge between them — through colour, pattern or subject.\n\nNot sure? Send a photo of the room — it says more than a thousand descriptions.",
     "seo_title_ru": "Картины в Казани", "seo_title_en": "Paintings in Kazan",
     "seo_description_ru": "Картины для дома в Казани: готовые работы и картины на заказ. Пейзажи с водой, цветы, абстракция — доставка через СДЭК или другую ТК."},
    {"source_id": "1502026", "name_ru": "Красноярск", "name_en": "Krasnoyarsk", "name_in_ru": "в Красноярске", "to": "в Красноярск",
     "title_ru": "Картины в Красноярске", "title_en": "Paintings in Krasnoyarsk",
     "intro_ru": "Енисей, скалы Столбов и тайга на горизонте — красноярцев сложно удивить пейзажем. Но можно порадовать.",
     "intro_en": "The Yenisei, the Stolby cliffs and taiga on the horizon — it’s hard to surprise Krasnoyarsk with a landscape. But you can delight it.",
     "body_ru": "Когда за городом такие виды, дома хочется продолжения: горной реки, соснового леса, неба с облаками. А можно пойти от противного и повесить южное море — для контраста с сибирским январем.\n\nМы подберем формат под вашу комнату и расскажем, как картина доберется через тысячи километров целой и невредимой.",
     "body_en": "With such views outside the city, home wants more of them: a mountain river, a pine forest, a cloudy sky. Or go the other way and hang a southern sea — for contrast with a Siberian January.\n\nWe’ll choose a format for your room and explain how the painting travels thousands of kilometres safely.",
     "seo_title_ru": "Картины в Красноярске", "seo_title_en": "Paintings in Krasnoyarsk",
     "seo_description_ru": "Картины в наличии и на заказ с доставкой в Красноярск. Пейзажи, море и другие сюжеты — надежная упаковка и отправка через СДЭК или другую ТК."},
    {"source_id": "520555", "name_ru": "Нижний Новгород", "name_en": "Nizhny Novgorod", "name_in_ru": "в Нижнем Новгороде", "to": "в Нижний Новгород",
     "title_ru": "Картины в Нижнем Новгороде", "title_en": "Paintings in Nizhny Novgorod",
     "intro_ru": "Там, где Ока впадает в Волгу, закаты такие, что хочется повесить их на стену. Мы поможем.",
     "intro_en": "Where the Oka flows into the Volga, the sunsets make you want to hang them on the wall. We can help.",
     "body_ru": "Нижний Новгород любит простор: Стрелка, откосы, бесконечная вода внизу. Широкие панорамные форматы здесь смотрятся особенно естественно — как вид с Чкаловской лестницы, только в гостиной.\n\nЕсли у вас старый дом в историческом центре, присмотритесь к классическим пейзажам и натюрмортам. Для новой квартиры подойдут светлые морские сюжеты и абстракция.",
     "body_en": "Nizhny Novgorod loves open space: the Strelka, the slopes, endless water below. Wide panoramic formats look especially natural here — like the view from the Chkalov Stairs, only in your living room.\n\nFor an old house in the historic centre, consider classic landscapes and still lifes; for a new flat, bright sea subjects and abstraction.",
     "seo_title_ru": "Картины в Нижнем Новгороде", "seo_title_en": "Paintings in Nizhny Novgorod",
     "seo_description_ru": "Картины для дома в Нижнем Новгороде: готовые работы и на заказ. Панорамные пейзажи, море, натюрморты — доставка через СДЭК или другую ТК."},
    {"source_id": "1508291", "name_ru": "Челябинск", "name_en": "Chelyabinsk", "name_in_ru": "в Челябинске", "to": "в Челябинск",
     "title_ru": "Картины в Челябинске", "title_en": "Paintings in Chelyabinsk",
     "intro_ru": "Южный Урал славится озерами — и немного воды на стене челябинскому дому точно не помешает.",
     "intro_en": "The Southern Urals are famous for lakes — and a little water on the wall won’t hurt a Chelyabinsk home.",
     "body_ru": "Челябинцы знают толк в характере: суровые зимы, промышленная история, озера и горы в паре часов езды. Картины здесь выбирают честные — без лишнего пафоса, зато с настроением.\n\nСпокойное озеро на рассвете, лесная тропа или яркая абстракция для рабочего кабинета — расскажите, что вам по душе, и мы найдем подходящую работу или обсудим новую.",
     "body_en": "Chelyabinsk knows character: harsh winters, industrial history, lakes and mountains a couple of hours away. Paintings here are chosen honestly — no pomp, but plenty of mood.\n\nA calm lake at dawn, a forest path or bright abstraction for the study — tell us what you like.",
     "seo_title_ru": "Картины в Челябинске", "seo_title_en": "Paintings in Chelyabinsk",
     "seo_description_ru": "Картины в наличии и на заказ с доставкой в Челябинск. Пейзажи с озерами, абстракция и другие сюжеты — отправка через СДЭК или другую ТК."},
    {"source_id": "479561", "name_ru": "Уфа", "name_en": "Ufa", "name_in_ru": "в Уфе", "to": "в Уфу",
     "title_ru": "Картины в Уфе", "title_en": "Paintings in Ufa",
     "intro_ru": "Уфа раскинулась на холмах над Белой — город, где вид из окна часто сам просится в раму.",
     "intro_en": "Ufa spreads over hills above the Belaya River — a city where the view from the window often asks to be framed.",
     "body_ru": "Холмы, река, много зелени летом — уфимцев сложно удивить природой, зато легко порадовать ее продолжением дома. Пейзажи с простором и светом здесь всегда к месту.\n\nА если хочется чего-то совсем другого — цветов в вазе, которые не завянут, или моря, до которого далеко, — это тоже можно устроить. Начните с простого «мне нравится».",
     "body_en": "Hills, a river, lots of green in summer — you can’t surprise Ufa with nature, but you can bring more of it home. Landscapes with space and light always fit here.\n\nOr go for something completely different — flowers that never wilt, or a far-away sea. Start with a simple “I like this”.",
     "seo_title_ru": "Картины в Уфе", "seo_title_en": "Paintings in Ufa",
     "seo_description_ru": "Картины для дома в Уфе: готовые работы и картины на заказ. Пейзажи, цветы, море — подберем формат, доставим через СДЭК или другую ТК."},
    {"source_id": "499099", "name_ru": "Самара", "name_en": "Samara", "name_in_ru": "в Самаре", "to": "в Самару",
     "title_ru": "Картины в Самаре", "title_en": "Paintings in Samara",
     "intro_ru": "У Самары одна из самых длинных набережных на Волге. Длинные панорамные картины здесь понимают с полуслова.",
     "intro_en": "Samara has one of the longest embankments on the Volga. Long panoramic paintings are understood here at once.",
     "body_ru": "Волга, Жигулевские горы на другом берегу, пляжи летом — самарцам есть с чем сравнивать. Поэтому к речным и морским пейзажам здесь особое отношение: хочется, чтобы вода на картине была «как настоящая».\n\nКупеческий центр с лепниной и новые районы на окраинах — разные интерьеры, разные решения. Пришлите фото, и мы подскажем, что подойдет именно вам.",
     "body_en": "The Volga, the Zhiguli Mountains across the river, summer beaches — Samara has plenty to compare with. River and sea landscapes are special here: the water on the canvas should look real.\n\nSend a photo of your room and we’ll suggest what suits you.",
     "seo_title_ru": "Картины в Самаре", "seo_title_en": "Paintings in Samara",
     "seo_description_ru": "Картины в наличии и на заказ с доставкой в Самару. Речные и морские пейзажи, панорамные форматы — отправка через СДЭК или другую ТК."},
    {"source_id": "501175", "name_ru": "Ростов-на-Дону", "name_en": "Rostov-on-Don", "name_in_ru": "в Ростове-на-Дону", "to": "в Ростов-на-Дону",
     "title_ru": "Картины в Ростове-на-Дону", "title_en": "Paintings in Rostov-on-Don",
     "intro_ru": "В Ростове много солнца, и картины здесь любят такие же — теплые, щедрые и живые.",
     "intro_en": "Rostov has lots of sun, and the paintings it loves are the same — warm, generous and alive.",
     "body_ru": "Южный характер чувствуется во всем: в широкой набережной Дона, в шумных улицах, в любви к ярким цветам. Сочные натюрморты, цветы и летние пейзажи в ростовском доме смотрятся как родные.\n\nА для тех, кто устал от жары, есть прохладные морские сюжеты и спокойная абстракция в голубых тонах. Выбирайте по настроению — или расскажите о своей идее.",
     "body_en": "The southern character is everywhere: the wide Don embankment, lively streets, a love of bright colours. Rich still lifes, flowers and summer landscapes feel at home in Rostov.\n\nFor those tired of the heat there are cool sea subjects and calm blue abstraction.",
     "seo_title_ru": "Картины в Ростове-на-Дону", "seo_title_en": "Paintings in Rostov-on-Don",
     "seo_description_ru": "Картины для дома в Ростове-на-Дону: готовые работы и на заказ. Яркие цветы, натюрморты, море — доставка через СДЭК или другую ТК."},
    {"source_id": "542420", "name_ru": "Краснодар", "name_en": "Krasnodar", "name_in_ru": "в Краснодаре", "to": "в Краснодар",
     "title_ru": "Картины в Краснодаре", "title_en": "Paintings in Krasnodar",
     "intro_ru": "Краснодар растет быстрее, чем успевают высыхать краски. Новым квартирам — новые картины.",
     "intro_en": "Krasnodar grows faster than paint dries. New flats deserve new paintings.",
     "body_ru": "Здесь много новостроек со светлыми стенами, которые так и просят акцента. Большая абстракция над диваном, пара цветочных работ в спальне или морской пейзаж в прихожей — чтобы море было ближе, чем два часа по трассе.\n\nЗелень, солнце и Кубань рядом делают краснодарцев смелее в цвете. Не бойтесь ярких сюжетов — мы подскажем, как их уравновесить.",
     "body_en": "There are many new builds with bright walls asking for an accent. Large abstraction above the sofa, a pair of flower works in the bedroom or a seascape in the hall — so the sea is closer than a two-hour drive.\n\nGreenery and sun make Krasnodar bolder with colour. Don’t be afraid of bright subjects.",
     "seo_title_ru": "Картины в Краснодаре", "seo_title_en": "Paintings in Krasnodar",
     "seo_description_ru": "Картины в наличии и на заказ с доставкой в Краснодар. Абстракция, цветы и морские пейзажи для новых квартир — отправка через СДЭК или другую ТК."},
    {"source_id": "1496153", "name_ru": "Омск", "name_en": "Omsk", "name_in_ru": "в Омске", "to": "в Омск",
     "title_ru": "Картины в Омске", "title_en": "Paintings in Omsk",
     "intro_ru": "Омск стоит на слиянии Иртыша и Оми, а вокруг — степь до горизонта. Простор здесь в крови.",
     "intro_en": "Omsk stands where the Irtysh meets the Om, with steppe to the horizon. Space is in its blood.",
     "body_ru": "Сибирская степь учит видеть красоту в широких горизонтах и большом небе. Такие пейзажи в омском доме смотрятся честно и спокойно — как будто окно открыли в июль.\n\nЗимой, когда город становится белым и строгим, хочется тепла: цветов, золотой осени, южного моря. Подберем работу под ваше настроение или обсудим картину на заказ.",
     "body_en": "The Siberian steppe teaches you to see beauty in wide horizons and a big sky. Such landscapes look honest and calm in an Omsk home — like a window opened onto July.\n\nIn winter, warmth is welcome: flowers, golden autumn, a southern sea.",
     "seo_title_ru": "Картины в Омске", "seo_title_en": "Paintings in Omsk",
     "seo_description_ru": "Картины для дома в Омске: готовые работы и картины на заказ. Пейзажи с простором, цветы, море — доставка через СДЭК или другую ТК."},
    {"source_id": "472045", "name_ru": "Воронеж", "name_en": "Voronezh", "name_in_ru": "в Воронеже", "to": "в Воронеж",
     "title_ru": "Картины в Воронеже", "title_en": "Paintings in Voronezh",
     "intro_ru": "Воронеж называют колыбелью русского флота, так что морские картины здесь вполне по традиции.",
     "intro_en": "Voronezh is called the cradle of the Russian navy, so sea paintings are quite traditional here.",
     "body_ru": "Зеленый, уютный, с большим водохранилищем посреди города — Воронеж располагает к спокойным сюжетам: летнему саду, реке в утреннем тумане, полю до горизонта. Черноземье вообще умеет быть щедрым на краски.\n\nМорской пейзаж в гостиной — отдельный воронежский жанр в нашем понимании. Ну а если хочется чего-то нового, обсудим картину по вашей идее.",
     "body_en": "Green, cosy, with a big reservoir in the middle — Voronezh invites calm subjects: a summer garden, a river in morning mist, a field to the horizon.\n\nA seascape in the living room is almost a local tradition. Or let’s discuss a painting based on your idea.",
     "seo_title_ru": "Картины в Воронеже", "seo_title_en": "Paintings in Voronezh",
     "seo_description_ru": "Картины в наличии и на заказ с доставкой в Воронеж. Морские и летние пейзажи, цветы — отправка через СДЭК или другую ТК по согласованию."},
    {"source_id": "511196", "name_ru": "Пермь", "name_en": "Perm", "name_in_ru": "в Перми", "to": "в Пермь",
     "title_ru": "Картины в Перми", "title_en": "Paintings in Perm",
     "intro_ru": "Пермь — город на Каме с любовью к искусству. Здесь знают, что хорошая картина начинается со взгляда.",
     "intro_en": "Perm is a city on the Kama with a love of art. People here know a good painting starts with a glance.",
     "body_ru": "Пермяков сложно удивить музеями, зато легко порадовать картиной, которая живет дома: у нее нет часов работы, и смотреть на нее можно хоть в пижаме. Уральский лес, камская вода, северный свет — прекрасные темы для пейзажа.\n\nЕсли тянет к современному, присмотритесь к абстракции и жидкому акрилу: разводы цвета здесь ведут себя почти как речные течения.",
     "body_en": "Perm has plenty of museums, but a painting at home has no opening hours — you can look at it in your pyjamas. Ural forest, Kama water and northern light are wonderful landscape themes.\n\nIf you lean modern, look at abstraction and fluid acrylic.",
     "seo_title_ru": "Картины в Перми", "seo_title_en": "Paintings in Perm",
     "seo_description_ru": "Картины для дома в Перми: готовые работы и на заказ. Уральские пейзажи, абстракция, жидкий акрил — доставка через СДЭК или другую ТК."},
    {"source_id": "472757", "name_ru": "Волгоград", "name_en": "Volgograd", "name_in_ru": "в Волгограде", "to": "в Волгоград",
     "title_ru": "Картины в Волгограде", "title_en": "Paintings in Volgograd",
     "intro_ru": "Волгоград тянется вдоль Волги на десятки километров. Длинные горизонты здесь привычны — и на стене тоже.",
     "intro_en": "Volgograd stretches along the Volga for dozens of kilometres. Long horizons are familiar here — on the wall too.",
     "body_ru": "Широкая река, степной ветер, жаркое лето — в Волгограде любят пространство и свет. Панорамные пейзажи и спокойное море в таком городе смотрятся естественно, а прохладные голубые тона помогают пережить июль.\n\nДля тех, кому хочется уюта, — цветы и натюрморты. Для тех, кому нужна энергия, — яркая абстракция. Остальное обсудим вместе.",
     "body_en": "A wide river, steppe wind, a hot summer — Volgograd loves space and light. Panoramic landscapes and a calm sea look natural here, and cool blue tones help survive July.\n\nFlowers for cosiness, bright abstraction for energy — the rest we’ll discuss together.",
     "seo_title_ru": "Картины в Волгограде", "seo_title_en": "Paintings in Volgograd",
     "seo_description_ru": "Картины в наличии и на заказ с доставкой в Волгоград. Панорамные пейзажи, море, цветы — отправка через СДЭК или другую ТК по согласованию."},
    {"source_id": "498677", "name_ru": "Саратов", "name_en": "Saratov", "name_in_ru": "в Саратове", "to": "в Саратов",
     "title_ru": "Картины в Саратове", "title_en": "Paintings in Saratov",
     "intro_ru": "Саратовская набережная над Волгой — готовый пейзаж. Осталось найти ему место дома.",
     "intro_en": "The Saratov embankment above the Volga is a ready-made landscape. It only needs a place at home.",
     "body_ru": "Волжские просторы, мост до Энгельса, старые улицы с деревянным кружевом — Саратов умеет быть живописным. Неудивительно, что речные пейзажи и городские сюжеты здесь выбирают охотно.\n\nА если дома хочется другого настроения — цветущего сада или морской прохлады, — у нас найдутся и такие работы. Пришлите фото стены, подскажем формат.",
     "body_en": "Volga views, the bridge to Engels, old streets with wooden lace — Saratov can be picturesque. River landscapes and city subjects are popular here.\n\nFor a different mood — a blooming garden or sea coolness — we have those too.",
     "seo_title_ru": "Картины в Саратове", "seo_title_en": "Paintings in Saratov",
     "seo_description_ru": "Картины для дома в Саратове: готовые работы и на заказ. Речные пейзажи, городские сюжеты, цветы — доставка через СДЭК или другую ТК."},
    {"source_id": "1488754", "name_ru": "Тюмень", "name_en": "Tyumen", "name_in_ru": "в Тюмени", "to": "в Тюмень",
     "title_ru": "Картины в Тюмени", "title_en": "Paintings in Tyumen",
     "intro_ru": "Тюмень называют первым русским городом в Сибири. Первой картине в новой квартире — самое время появиться.",
     "intro_en": "Tyumen is called the first Russian city in Siberia. Time for the first painting in your new flat.",
     "body_ru": "Город активно строится, и многие тюменцы как раз обживают новые квартиры. Светлые стены — лучший фон для картины: морской пейзаж, мягкие цветы или графичная абстракция сразу делают пространство своим.\n\nНабережная Туры, мост Влюбленных, сибирские зимы — вдохновения хватает. Подберем готовую работу или обсудим картину под вашу комнату.",
     "body_en": "The city is growing, and many residents are settling into new flats. Bright walls are the best background for a painting: a seascape, soft flowers or graphic abstraction make a space your own.\n\nWe’ll find a ready work or discuss a painting for your room.",
     "seo_title_ru": "Картины в Тюмени", "seo_title_en": "Paintings in Tyumen",
     "seo_description_ru": "Картины в наличии и на заказ с доставкой в Тюмень. Морские пейзажи, цветы, абстракция для новых квартир — отправка через СДЭК или другую ТК."},
]
