"""Стартовые отзывы (комплект заказчика). Фото — кадры из утвержденного листа; даты демонстрационные: случайные за последние 3 года, для каждого сайта свои."""

REVIEWS = [
    {"author_ru": 'Анна', "author_en": 'Anna', "city_ru": 'Новосибирск', "city_en": 'Novosibirsk',
     "text_ru": 'Очень боялась, что картина «не подружится» с нашей спальней, но она, кажется, подружилась даже с тумбочкой. Цвета мягкие, живые, без крика — ровно то, что хотелось для спокойного утра. Отдельное спасибо за упаковку: открывали заказ как маленький праздник.',
     "text_en": 'I was so afraid the painting would not “make friends” with our bedroom, but it seems to have befriended even the nightstand. The colours are soft and alive, never loud — exactly what I wanted for a calm morning. Special thanks for the packaging: we opened the parcel like a small celebration.',
     "date": "2025-08-13", "photo": "mirame_review_01.jpg", "painting_note": 'Букет пионов'},
    {"author_ru": 'Ирина', "author_en": 'Irina', "city_ru": 'Томск', "city_en": 'Tomsk',
     "text_ru": 'Нужна была картина, которая добавит воздуху комнате, и море справилось на отлично. Вживую работа намного глубже, чем на фото: свет, вода, настроение — всё очень естественно. Теперь это первое, на что смотрят гости.',
     "text_en": 'I needed a painting that would give the room some air, and the sea did it perfectly. In person the work is far deeper than in the photo: the light, the water, the mood all feel natural. Now it is the first thing guests look at.',
     "date": "2026-06-01", "photo": "mirame_review_02.jpg", "painting_note": 'Морской пейзаж'},
    {"author_ru": 'Мария и Егор', "author_en": 'Maria and Egor', "city_ru": 'Красноярск', "city_en": 'Krasnoyarsk',
     "text_ru": 'Заказали портрет нашего любимца и получили не просто картину, а домашнего героя на стене. Узнаваемость отличная, взгляд тёплый, и при этом всё художественно, без ощущения «фото на холсте». Смеёмся, что теперь у собаки дома собственная галерея.',
     "text_en": 'We ordered a portrait of our beloved pet and got not just a painting but a hero of the house on the wall. The likeness is excellent, the gaze is warm, and it is still artistic, without the feeling of a “photo on canvas”. We joke that the dog now has a gallery of his own.',
     "date": "2024-08-06", "photo": "mirame_review_03.jpg", "painting_note": 'Портрет собаки'},
    {"author_ru": 'Ольга', "author_en": 'Olga', "city_ru": 'Екатеринбург', "city_en": 'Yekaterinburg',
     "text_ru": 'Картина приехала прекрасно упакованной, без сюрпризов, кроме одного — она оказалась ещё красивее, чем ожидалось. Очень нравится солнечное настроение и лёгкость сюжета. Повесили в кухне, и стало заметно уютнее.',
     "text_en": 'The painting arrived wonderfully packed, with no surprises except one — it turned out even more beautiful than expected. I love the sunny mood and the lightness of the scene. We hung it in the kitchen, and it became noticeably cosier.',
     "date": "2023-10-07", "photo": "mirame_review_04.jpg", "painting_note": 'Городской южный сюжет'},
    {"author_ru": 'Светлана', "author_en": 'Svetlana', "city_ru": 'Москва', "city_en": 'Moscow',
     "text_ru": 'Искала что-то спокойное, женственное и современное для гостиной. Картина отлично вписалась и не спорит с интерьером, а мягко его собирает. Люблю вещи, которые не шумят, а создают атмосферу — это именно такой случай.',
     "text_en": 'I was looking for something calm, feminine and modern for the living room. The painting fits in perfectly and does not argue with the interior; it gently pulls it together. I love things that do not make noise but create atmosphere — this is exactly such a case.',
     "date": "2026-02-06", "photo": "mirame_review_05.jpg", "painting_note": 'Фигура в светлых тонах'},
    {"author_ru": 'Елена', "author_en": 'Elena', "city_ru": 'Казань', "city_en": 'Kazan',
     "text_ru": 'На словах это просто натюрморт, а на деле — витамин D для комнаты. Очень живые мазки, красивый свет, приятная фактура. Работу повесили рядом с обеденной зоной, и она каждый день делает кухню бодрее.',
     "text_en": 'In words it is just a still life, but in reality it is vitamin D for the room. Very lively brushstrokes, beautiful light, a pleasant texture. We hung it near the dining area, and it makes the kitchen livelier every day.',
     "date": "2025-08-28", "photo": "mirame_review_06.jpg", "painting_note": 'Лимоны / натюрморт'},
    {"author_ru": 'Дарья', "author_en": 'Daria', "city_ru": 'Санкт-Петербург', "city_en": 'Saint Petersburg',
     "text_ru": 'Заказала картину в подарок сестре, и кот на холсте буквально украл весь вечер. Работа ироничная, живая и очень тёплая. Теперь сестра говорит, что это самый разговорчивый кот в доме, хотя он вообще-то нарисованный.',
     "text_en": 'I ordered the painting as a gift for my sister, and the cat on the canvas simply stole the whole evening. The work is ironic, lively and very warm. Now my sister says it is the chattiest cat in the house, although it is actually painted.',
     "date": "2024-09-17", "photo": "mirame_review_07.jpg", "painting_note": 'Портрет кота'},
    {"author_ru": 'Наталья', "author_en": 'Natalia', "city_ru": 'Омск', "city_en": 'Omsk',
     "text_ru": 'Нужен был светлый акцент в спальню, без лишней драматичности. Абстракция получилась очень нежной, воздушной и современной. Понравилось, что работу можно рассматривать долго — каждый раз находишь новый ритм и оттенок.',
     "text_en": 'I needed a light accent for the bedroom, without extra drama. The abstract turned out very tender, airy and modern. I liked that you can look at the work for a long time — every time you find a new rhythm and shade.',
     "date": "2025-07-21", "photo": "mirame_review_08.jpg", "painting_note": 'Пастельная абстракция'},
    {"author_ru": 'Андрей', "author_en": 'Andrey', "city_ru": 'Сочи', "city_en": 'Sochi',
     "text_ru": 'Картина создаёт ощущение отпуска без чемоданов и очередей в аэропорту. Очень достойно смотрится над консолью, хорошо держит пространство стены. Качество холста и оформления на хорошем уровне.',
     "text_en": 'The painting creates the feeling of a holiday without suitcases and airport queues. It looks very dignified above the console and holds the wall space well. The quality of the canvas and the framing is good.',
     "date": "2026-02-11", "photo": "mirame_review_09.jpg", "painting_note": 'Тосканский пейзаж'},
    {"author_ru": 'Юлия', "author_en": 'Yulia', "city_ru": 'Тюмень', "city_en": 'Tyumen',
     "text_ru": 'Искали что-то доброе для детской, без аляповатости. Эта работа идеально подошла: мягкие цвета, спокойный сюжет, ощущение лета и света. Дочка каждый вечер смотрит на картину перед сном — лучшая рекомендация.',
     "text_en": 'We were looking for something kind for the nursery, without garishness. This work was a perfect fit: soft colours, a calm subject, a feeling of summer and light. My daughter looks at the painting every evening before bed — the best recommendation.',
     "date": "2026-06-13", "photo": "mirame_review_10.jpg", "painting_note": 'Детский морской сюжет'},
]
