# Generated by Django 5.2.17 on 2026-09-29 11:24

import django.core.files.storage
import django.db.models.deletion
import leads.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("closed", "Закрыта"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("general", "Общий заказ"),
                            ("category", "Заказ по рубрике"),
                            ("painting", "Заказ картины"),
                            ("similar", "Заказать похожую"),
                            ("custom", "Картина на заказ"),
                            ("certificate", "Подарочный сертификат"),
                            ("delivery", "Вопрос о доставке"),
                            ("question", "Вопрос"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Тип обращения",
                    ),
                ),
                (
                    "painting_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Название картины на момент заявки",
                    ),
                ),
                (
                    "painting_status",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Состояние картины на момент заявки",
                    ),
                ),
                (
                    "source_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Страница, с которой отправлено",
                    ),
                ),
                (
                    "lang",
                    models.CharField(default="ru", max_length=2, verbose_name="Язык"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Имя")),
                (
                    "contact_method",
                    models.CharField(
                        choices=[
                            ("phone", "Телефон"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("max", "MAX"),
                            ("email", "Email"),
                        ],
                        max_length=12,
                        verbose_name="Способ связи",
                    ),
                ),
                ("contact", models.CharField(max_length=160, verbose_name="Контакт")),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="Город"),
                ),
                (
                    "deadline",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Желаемый срок"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "size_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Не указан"),
                            ("standard", "Из списка"),
                            ("custom", "Свой размер"),
                            ("undecided", "Пока не определился"),
                        ],
                        max_length=12,
                        verbose_name="Желаемый размер",
                    ),
                ),
                (
                    "size_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="Ширина, см",
                    ),
                ),
                (
                    "size_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="Высота, см",
                    ),
                ),
                (
                    "size_orientation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("horizontal", "Горизонтальное"),
                            ("vertical", "Вертикальное"),
                            ("square", "Квадрат"),
                        ],
                        max_length=12,
                        verbose_name="Расположение",
                    ),
                ),
                (
                    "certificate_amount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номинал сертификата"
                    ),
                ),
                (
                    "certificate_format",
                    models.CharField(
                        blank=True,
                        choices=[("electronic", "Электронный"), ("print", "Печатный")],
                        max_length=12,
                        verbose_name="Формат сертификата",
                    ),
                ),
                (
                    "manager_note",
                    models.TextField(blank=True, verbose_name="Заметка менеджера"),
                ),
                (
                    "notification_error",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ошибка уведомления"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Получена"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменена"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.category",
                        verbose_name="Рубрика",
                    ),
                ),
                (
                    "painting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.painting",
                        verbose_name="Картина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url=None,
                            location=pathlib.PurePosixPath(
                                "/home/user/art/var/a/private"
                            ),
                        ),
                        upload_to=leads.models.attachment_path,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Имя файла"
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(default=0, verbose_name="Размер, байт"),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение",
                "verbose_name_plural": "Вложения",
            },
        ),
    ]
