# Generated by Django 5.2.17 on 2026-09-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="certificate_recipient",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Имя получателя / подпись"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="consent_given",
            field=models.BooleanField(
                default=False, verbose_name="Согласие на обработку данных"
            ),
        ),
    ]
