# Generated by Django 5.2.17 on 2026-09-29 11:24

import core.i18n
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=80, unique=True, verbose_name="Ключ"),
                ),
                (
                    "group",
                    models.CharField(blank=True, max_length=40, verbose_name="Группа"),
                ),
                (
                    "hint",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Где используется"
                    ),
                ),
                ("value_ru", models.TextField(verbose_name="Текст (RU)")),
                ("value_en", models.TextField(blank=True, verbose_name="Текст (EN)")),
            ],
            options={
                "verbose_name": "Надпись интерфейса",
                "verbose_name_plural": "Надписи интерфейса",
                "ordering": ["group", "key"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Messenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Название")),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("max", "MAX"),
                            ("vk", "VK"),
                            ("viber", "Viber"),
                            ("email", "Email"),
                            ("phone", "Телефон"),
                        ],
                        max_length=20,
                        verbose_name="Значок",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="https://t.me/…, https://wa.me/…, mailto:…, tel:…",
                        max_length=255,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
            ],
            options={
                "verbose_name": "Мессенджер",
                "verbose_name_plural": "Мессенджеры и каналы связи",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_path",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="Старый адрес"
                    ),
                ),
                (
                    "new_path",
                    models.CharField(max_length=500, verbose_name="Новый адрес"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Перенаправление 301",
                "verbose_name_plural": "Перенаправления 301",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeoTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("painting_available", "Картина — в наличии"),
                            ("painting_custom", "Картина — под заказ"),
                            ("painting_sold", "Картина — продана"),
                            ("category", "Рубрика"),
                            ("article", "Статья"),
                            ("page", "Страница"),
                            ("list_page", "Страница списка N > 1"),
                        ],
                        max_length=40,
                        unique=True,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Title (RU), после «{brand} |»",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Title (EN), после «{brand} |»",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Description (RU)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
            ],
            options={
                "verbose_name": "SEO-шаблон",
                "verbose_name_plural": "SEO-шаблоны по типам страниц",
                "ordering": ["kind"],
            },
        ),
        migrations.CreateModel(
            name="SharedBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(max_length=60, unique=True, verbose_name="Ключ"),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Название в админке"),
                ),
                (
                    "usage",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Где используется"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок (RU)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок (EN)"
                    ),
                ),
                ("text_ru", models.TextField(blank=True, verbose_name="Текст (RU)")),
                ("text_en", models.TextField(blank=True, verbose_name="Текст (EN)")),
                (
                    "button_ru",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Кнопка (RU)"
                    ),
                ),
                (
                    "button_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Кнопка (EN)"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
            ],
            options={
                "verbose_name": "Сквозной блок",
                "verbose_name_plural": "Сквозные блоки",
                "ordering": ["name"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name_ru",
                    models.CharField(
                        default="МираМе", max_length=80, verbose_name="Название (RU)"
                    ),
                ),
                (
                    "brand_name_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "slogan_ru",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Слоган (RU)"
                    ),
                ),
                (
                    "slogan_en",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Слоган (EN)"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="brand/", verbose_name="Логотип"
                    ),
                ),
                (
                    "logo_on_dark",
                    models.ImageField(
                        blank=True,
                        upload_to="brand/",
                        verbose_name="Логотип для темного фона",
                    ),
                ),
                (
                    "logo_alt_ru",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Альтернативный текст логотипа (RU)",
                    ),
                ),
                (
                    "logo_alt_en",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Альтернативный текст логотипа (EN)",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Квадратное PNG-изображение от 192×192 px.",
                        upload_to="brand/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "logo_contains_slogan",
                    models.BooleanField(
                        default=True,
                        help_text="Тогда слоган не дублируется отдельной надписью рядом с логотипом.",
                        verbose_name="Слоган уже есть внутри файла логотипа",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Например, https://mirame.ru — без слеша в конце. Используется в canonical, sitemap, robots.txt, hreflang, Open Graph и разметке.",
                        verbose_name="Основной адрес сайта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "address_ru",
                    models.CharField(
                        blank=True,
                        help_text="Заполняйте только при реальной точке приема клиентов. Личного приема нет — оставьте пустым.",
                        max_length=255,
                        verbose_name="Адрес (RU)",
                    ),
                ),
                (
                    "address_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Адрес (EN)"
                    ),
                ),
                (
                    "hours_ru",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Режим ответа (RU)"
                    ),
                ),
                (
                    "hours_en",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Режим ответа (EN)"
                    ),
                ),
                (
                    "geography_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="География работы (RU)"
                    ),
                ),
                (
                    "geography_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="География работы (EN)"
                    ),
                ),
                (
                    "copyright_ru",
                    models.CharField(
                        blank=True,
                        default="© {year} {brand}",
                        max_length=160,
                        verbose_name="Копирайт (RU)",
                    ),
                ),
                (
                    "copyright_en",
                    models.CharField(
                        blank=True,
                        default="© {year} {brand}",
                        max_length=160,
                        verbose_name="Копирайт (EN)",
                    ),
                ),
                (
                    "show_sold_in_catalog",
                    models.BooleanField(
                        default=True,
                        help_text="Если выключено, проданные работы видны только в разделе SOLD.",
                        verbose_name="Показывать проданные в рубриках каталога",
                    ),
                ),
                (
                    "painting_prefix_ru",
                    models.CharField(
                        default="картина",
                        max_length=40,
                        verbose_name="Префикс адреса картины (RU)",
                    ),
                ),
                (
                    "painting_prefix_en",
                    models.CharField(
                        default="painting",
                        max_length=40,
                        verbose_name="Префикс адреса картины (EN)",
                    ),
                ),
                (
                    "per_page",
                    models.PositiveSmallIntegerField(
                        default=24,
                        validators=[django.core.validators.MinValueValidator(4)],
                        verbose_name="Картин на странице списка",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="₽", max_length=8, verbose_name="Валюта цен"
                    ),
                ),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True,
                        upload_to="certificate/",
                        verbose_name="Изображение сертификата",
                    ),
                ),
                (
                    "certificate_custom_amount",
                    models.BooleanField(
                        default=False,
                        verbose_name="Разрешить произвольную сумму сертификата",
                    ),
                ),
                (
                    "certificate_electronic",
                    models.BooleanField(
                        default=False, verbose_name="Доступен электронный сертификат"
                    ),
                ),
                (
                    "certificate_print",
                    models.BooleanField(
                        default=False, verbose_name="Доступен печатный сертификат"
                    ),
                ),
                (
                    "map_tiles_url",
                    models.CharField(
                        default="https://tile.openstreetmap.org/{z}/{x}/{y}.png",
                        max_length=255,
                        verbose_name="Адрес тайлов карты",
                    ),
                ),
                (
                    "map_attribution",
                    models.CharField(
                        default='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
                        max_length=255,
                        verbose_name="Подпись источника карты",
                    ),
                ),
                (
                    "notify_emails",
                    models.CharField(
                        blank=True,
                        help_text="Несколько адресов — через запятую.",
                        max_length=500,
                        verbose_name="Email для уведомлений о заявках",
                    ),
                ),
                (
                    "robots_txt",
                    models.TextField(
                        default="User-agent: *\nDisallow: /{admin_path}\nDisallow: /api/v1/import/\nDisallow: /lead/\n\nSitemap: {site_url}/sitemap.xml\n",
                        verbose_name="robots.txt",
                    ),
                ),
                (
                    "robots_disallow_all_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Нужно только если в robots.txt есть «Disallow: /». Для рабочего сайта не используется.",
                        verbose_name="Подтверждаю закрытие всего сайта от индексации",
                    ),
                ),
                (
                    "yandex_verification",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Код Яндекс Вебмастера"
                    ),
                ),
                (
                    "google_verification",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Код Google Search Console",
                    ),
                ),
                (
                    "yandex_metrika_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Номер счетчика Яндекс Метрики",
                    ),
                ),
                (
                    "ga4_id",
                    models.CharField(
                        blank=True,
                        help_text="Вида G-XXXXXXX",
                        max_length=20,
                        verbose_name="Идентификатор GA4",
                    ),
                ),
                (
                    "analytics_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Включить счетчики"
                    ),
                ),
                (
                    "sitemap_generated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Последняя генерация sitemap.xml",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Общие настройки",
                "verbose_name_plural": "Общие настройки",
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StandardSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Меньшая сторона, см",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Большая сторона, см",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("rect", "Прямоугольные"),
                            ("square", "Квадратные"),
                            ("pano", "Панорамные"),
                        ],
                        default="rect",
                        max_length=10,
                        verbose_name="Группа",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
            ],
            options={
                "verbose_name": "Стандартный размер",
                "verbose_name_plural": "Размеры картин (общий список)",
                "ordering": ["order", "width", "height"],
            },
        ),
    ]
