# Generated by Django 5.2.17 on 2026-09-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="consent_checkbox",
            field=models.BooleanField(
                default=True,
                help_text="Отправка возможна только с отметкой согласия. Текст — надпись form.consent; ссылка — страница, указанная ниже.",
                verbose_name="Галочка согласия в формах",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_note_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Подпись в шапке (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_note_ru",
            field=models.CharField(
                blank=True,
                help_text="Короткая строка справа в шапке внутренних страниц.",
                max_length=120,
                verbose_name="Подпись в шапке (RU)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="privacy_page_url",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Ссылка на политику обработки данных",
            ),
        ),
    ]
