# Generated by Django 5.2.17 on 2026-09-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_consent_checkbox_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="address_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Например, 55.751244. Можно взять в Яндекс Картах: правый клик по точке → координаты.",
                max_digits=9,
                null=True,
                verbose_name="Широта адреса",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота адреса",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cdek_calc_url",
            field=models.URLField(
                blank=True,
                default="https://www.cdek.ru/ru/calculate/",
                verbose_name="СДЭК: калькулятор стоимости",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cdek_offices_url",
            field=models.URLField(
                blank=True,
                default="https://www.cdek.ru/ru/offices/",
                verbose_name="СДЭК: пункты выдачи",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cdek_tracking_url",
            field=models.URLField(
                blank=True,
                default="https://www.cdek.ru/ru/tracking/",
                verbose_name="СДЭК: отслеживание отправления",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address_ru",
            field=models.CharField(
                blank=True,
                help_text="Адрес для страницы «Контакты» и разметки. Если заполнены координаты, на странице контактов показывается карта с отметкой.",
                max_length=255,
                verbose_name="Адрес (RU)",
            ),
        ),
    ]
