# Generated by Django 5.2.17 on 2026-09-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contacts_map_cdek_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="indexnow_enabled",
            field=models.BooleanField(
                default=False,
                help_text="При публикации, обновлении и удалении страницы адрес автоматически отправляется в IndexNow. Это ускоряет уведомление робота, но не гарантирует индексацию. Включайте на рабочем домене.",
                verbose_name="Сообщать Яндексу об изменениях (IndexNow)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="indexnow_key",
            field=models.CharField(
                blank=True,
                help_text="Пусто — ключ будет создан при включении. Файл ключа доступен по адресу «адрес сайта/ключ.txt».",
                max_length=64,
                verbose_name="Ключ IndexNow",
            ),
        ),
    ]
