# Generated by Django 5.2.17 on 2026-10-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_indexnow"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="menu_in_footer",
            field=models.BooleanField(
                default=True,
                help_text="Пункты, отмеченные «Повторять в футере», выводятся в подвале.",
                verbose_name="Повторять меню в подвале",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="menu_in_header",
            field=models.BooleanField(
                default=True,
                help_text="Показывать меню в шапке сайта.",
                verbose_name="Верхнее меню",
            ),
        ),
    ]
