# Generated by Django 5.2.17 on 2026-10-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_menu_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(default="zh", max_length=5, verbose_name="Язык"),
                ),
                (
                    "target",
                    models.CharField(
                        db_index=True, max_length=80, verbose_name="Объект"
                    ),
                ),
                ("field", models.CharField(max_length=60, verbose_name="Поле")),
                ("text", models.TextField(blank=True, verbose_name="Перевод")),
            ],
            options={
                "verbose_name": "Перевод",
                "verbose_name_plural": "Переводы (китайский)",
                "ordering": ["target", "field"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lang", "target", "field"), name="translation_unique"
                    )
                ],
            },
        ),
    ]
