"""Надписи интерфейса на китайском: ключ → текст.

Правятся в «Переводы (китайский)» (объект label:<ключ>, поле value); значение из таблицы важнее этого списка.
"""
LABELS_ZH = {
    "nav.menu": "菜单",
    "nav.close": "关闭",
    "nav.home": "首页",
    "nav.breadcrumbs": "面包屑导航",
    "nav.lang_switch": "English",
    "nav.skip": "跳到正文",
    "nav.messengers": "联系我们",
    "nav.guides": "实用指南",
    "nav.studio": "关于工作室",
    "nav.back_to": "返回栏目",
    "btn.order": "订购画作",
    "btn.order_this": "订购这幅画",
    "btn.discuss": "洽谈订单",
    "btn.similar": "订购同款",
    "btn.certificate": "礼品券",
    "btn.more": "显示更多",
    "btn.all_works": "全部作品",
    "btn.read": "阅读",
    "btn.to_catalog": "前往目录",
    "btn.view": "查看",
    "status.available": "现货",
    "status.custom": "接受定制",
    "status.sold": "已售出",
    "status.sold_badge": "SOLD",
    "price.on_request": "价格面议",
    "spec.size": "尺寸",
    "spec.technique": "技法",
    "spec.base": "画材",
    "spec.framing": "装裱",
    "spec.year": "年份",
    "spec.status": "状态",
    "spec.sku": "编号",
    "spec.author": "作者",
    "spec.price": "价格",
    "painting.photos": "作品照片",
    "painting.zoom": "放大图片",
    "painting.sold_note": "这幅作品已售出，但可以参照它的风格订制一幅新画。",
    "painting.custom_note": "这幅作品仅作示例展示，新画将根据您的想法单独商定。",
    "painting.hint.available": "请告诉我们您对尺寸和装裱的要求。",
    "painting.hint.custom": "尺寸和工期单独商定。",
    "painting.hint.sold": "作品已售出，我们可以按相似的意境为您创作一幅新画。",
    "painting.sold_heading": "这幅作品已售出",
    "painting.details": "细节",
    "painting.whole": "画作全貌",
    "painting.status_page_sold": "SOLD / 已售出",
    "catalog.list_title": "现货与定制",
    "catalog.list_hint": "选择一幅画，了解更多",
    "catalog.rubric_works": "本栏目的画作",
    "catalog.all": "完整目录",
    "catalog.order_similar_hint": "订购同款",
    "contacts.phone": "电话",
    "contacts.email": "电子邮箱",
    "contacts.message": "留言",
    "contacts.open_form": "打开咨询表单",
    "contacts.open_messenger": "打开即时通讯软件",
    "contacts.other": "其他联系方式",
    "contacts.write_to": "通过以下方式联系：",
    "contacts.form_title": "联系我们",
    "map.your_city": "您的城市",
    "map.empty_marker_note": "确认的销售记录添加后，标记会显示在这里。",
    "map.country": "国家",
    "form.sample_note": "目录中的任何一幅画都可以作为样例：我们会为您单独创作一幅相似的作品。",
    "catalog.sample_badge": "样例 · 可创作同款",
    "footer.certificate": "礼品券",
    "map.delivery_title": "配送至该城市",
    "map.delivery_hint": "我们通过 CDEK 或经您同意的其他运输公司发货。运费另行支付；路线、包装和时间在发货前商定。",
    "map.cdek_offices": "CDEK 自提点",
    "map.cdek_calc": "在 CDEK 网站估算运费",
    "map.cdek_track": "查询运单",
    "map.cdek_note": "CDEK 网站上的估算仅供参考，最终费用将与您确认。",
    "map.discuss_city": "咨询配送至该城市",
    "map.city_page": "城市页面",
    "delivery.cdek_title": "CDEK 实用链接",
    "contacts.map_title": "如何找到我们",
    "contacts.address": "地址",
    "contacts.open_map": "在 Yandex 地图中打开",
    "contacts.route": "规划路线",
    "cities.open": "了解详情",
    "cities.delivery_title": "配送与收货：",
    "cities.contacts_title": "联系我们",
    "cities.hours": "营业时间",
    "cities.works_title": "现货与定制画作",
    "cities.reviews_title": "来自该城市的评价",
    "cities.other": "其他城市",
    "footer.all_contacts": "全部联系方式",
    "map.city_note": "我们的画作已经寄到过这里。",
    "reviews.next": "更多故事",
    "painting.more_in_category": "本栏目更多作品",
    "catalog.subcategories": "子栏目",
    "catalog.works": "作品",
    "catalog.page": "页码",
    "catalog.next": "下一页",
    "catalog.prev": "上一页",
    "catalog.pagination": "列表分页",
    "catalog.order_cta": "任何题材都可以商量",
    "form.title.general": "订购画作",
    "form.title.category": "订购本栏目画作",
    "form.title.painting": "这幅画的订购申请",
    "form.title.similar": "订购同款画作",
    "form.title.certificate": "礼品券申请",
    "form.title.delivery": "配送咨询",
    "form.similar_note": "洽谈的是参照所选作品创作的新画，而不是已售出的原作。",
    "form.context": "您咨询的是",
    "form.name": "姓名",
    "form.method": "希望如何联系您",
    "form.contact": "联系方式",
    "form.contact.phone": "手机号码",
    "form.contact.telegram": "Telegram 用户名或手机号",
    "form.contact.whatsapp": "WhatsApp 号码",
    "form.contact.max": "MAX 号码或链接",
    "form.contact.email": "电子邮箱地址",
    "form.method.phone": "电话",
    "form.method.telegram": "Telegram",
    "form.method.whatsapp": "WhatsApp",
    "form.method.max": "MAX",
    "form.method.email": "电子邮箱",
    "form.more": "补充详情",
    "form.city": "城市",
    "form.deadline": "期望时间",
    "form.comment": "留言",
    "form.file": "参考图片",
    "form.file_hint": "JPG、PNG 或 WEBP 格式，不超过 10 MB",
    "form.optional": "选填",
    "form.required": "必填",
    "form.submit": "提交申请",
    "form.sending": "正在提交…",
    "form.consent": "提交表单即表示您同意我们处理所填写的信息，以便回复您的咨询。",
    "form.error.required": "请填写此项",
    "form.error.email": "请检查邮箱地址",
    "form.error.phone": "请检查电话号码",
    "form.error.file_type": "请使用 JPG、PNG 或 WEBP 文件",
    "form.error.file_size": "文件超过 10 MB",
    "form.error.size": "请检查尺寸：应为大于零的厘米数",
    "form.error.consent": "需要您同意信息处理",
    "form.kicker": "订购画作",
    "form.selected": "所选作品",
    "form.attach": "附上参考照片",
    "form.required_note": "带星号的项目为必填。我们会通过您选择的方式联系您。",
    "form.name_ph": "您的姓名",
    "form.city_ph": "选填",
    "form.comment_ph": "请描述您想要的画作",
    "form.deadline_ph": "如有需要",
    "form.privacy_link": "个人信息处理政策",
    "cert.recipient": "收礼人姓名 / 题字",
    "cert.recipient_ph": "选填",
    "cert.choose": "选择面额",
    "cert.visual_title": "礼品券",
    "cert.visual_note": "可兑换收礼人挑选的画作",
    "cert.visual_under": "适用于现货作品或定制订单。",
    "cert.terms_link": "礼品券条款",
    "cert.hint": "我们会与您商定礼品券金额和装帧的要求。",
    "form.error.generic": "请检查标出的项目",
    "form.ok_title": "申请已提交",
    "size.title": "新画的期望尺寸",
    "size.none": "未选择",
    "size.custom": "自定义尺寸",
    "size.undecided": "暂未确定",
    "size.width": "宽度（厘米）",
    "size.height": "高度（厘米）",
    "size.orientation": "方向",
    "size.horizontal": "横向",
    "size.vertical": "竖向",
    "size.standard_group": "标准规格",
    "size.actual": "原作尺寸",
    "cert.nominal": "面额",
    "cert.custom_amount": "其他金额",
    "cert.format": "形式",
    "cert.electronic": "电子版",
    "cert.print": "纸质版",
    "cert.no_nominals": "面额在洽谈时确定。",
    "map.list": "地图上的城市",
    "map.search": "查找城市",
    "map.all_countries": "所有国家",
    "map.cities_count": "座城市",
    "reviews.city": "城市",
    "studio.illustration": "插图",
    "guides.title": "实用指南",
    "guides.related": "延伸阅读",
    "footer.sections": "栏目",
    "footer.contacts": "联系我们",
    "footer.service": "信息",
    "error404.title": "页面不存在",
    "error404.text": "没有这个页面，或者页面已搬家。请看看目录，或返回首页。",
}
