"""Стартовое содержимое страницы «Сотрудничество» для МираМе (A) и ХолСтори (D): RU, EN, 中文.

Тексты и положение блоков — по утверждённым макетам; сайты наполняются независимо.
"""

PAGE = {
    "a": {
        "title_ru": "Сотрудничество", "title_en": "Cooperation", "nav_title_ru": "Сотрудничество", "nav_title_en": "Cooperation",
        "slug_ru": "сотрудничество", "slug_en": "cooperation",
        "seo_title_ru": "Сотрудничество с дизайнерами и архитекторами", "seo_title_en": "Cooperation with designers and architects",
        "seo_description_ru": "Приглашаем дизайнеров, архитекторов и декораторов: готовые картины и работы под ваш проект, доставка через СДЭК или согласованную ТК.",
        "seo_description_en": "We invite designers, architects and decorators: ready-made paintings and works for your project, delivery via CDEK or an agreed carrier.",
        "zh": {"title": "合作", "nav_title": "合作", "seo_title": "与设计师和建筑师合作",
               "seo_description": "诚邀设计师、建筑师和软装师：现成画作与按项目创作的作品，通过 CDEK 或商定的运输公司发货。"},
    },
    "d": {
        "title_ru": "Сотрудничество", "title_en": "Cooperation", "nav_title_ru": "Сотрудничество", "nav_title_en": "Cooperation",
        "slug_ru": "сотрудничество", "slug_en": "cooperation",
        "seo_title_ru": "Сотрудничество с дизайнерами, архитекторами и комплектаторами", "seo_title_en": "Cooperation with designers, architects and procurement specialists",
        "seo_description_ru": "HolStori работает с дизайнерами интерьера, архитекторами и студиями: готовые произведения и работы по ТЗ для жилых и коммерческих объектов.",
        "seo_description_en": "HolStori works with interior designers, architects and studios: ready works and works to a brief for residential and commercial projects.",
        "zh": {"title": "合作", "nav_title": "合作", "seo_title": "与设计师、建筑师和室内配置专业人员合作",
               "seo_description": "HolStori 与室内设计师、建筑师和工作室合作：为住宅和商业项目提供现成作品及按技术要求创作的作品。"},
    },
}

CONTENT = {
    "a": {
        "scalars": {
            "hero_mode": "split",
            "hero_kicker_ru": "Для профессионалов интерьера", "hero_kicker_en": "For interior professionals",
            "h1_ru": "Сотрудничество", "h1_en": "Cooperation",
            "hero_subtitle_ru": "Приглашаем дизайнеров, архитекторов и декораторов к сотрудничеству",
            "hero_subtitle_en": "We invite designers, architects and decorators to work with us",
            "hero_lead_ru": "Готовые картины и работы по вашему проекту — под конкретное пространство.",
            "hero_lead_en": "Ready-made paintings and works for your project — made for a specific space.",
            "hero_button_ru": "Обсудить проект", "hero_button_en": "Discuss a project",
            "hero_image_alt_ru": "Светлая гостиная с морским пейзажем на стене и оливковым деревом у окна",
            "hero_image_alt_en": "A bright living room with a seascape on the wall and an olive tree by the window",
            "cta_title_ru": "Открыты к долгосрочному сотрудничеству", "cta_title_en": "Open to long-term cooperation",
            "cta_text_ru": "Нам интересны и разовые проекты, и постоянная работа с дизайнерами и студиями. Если у вас есть проект — пришлите его нам, и мы предложим подходящий формат без лишней бюрократии.",
            "cta_text_en": "We are interested in one-off projects and in regular work with designers and studios. If you have a project, send it to us and we will offer a suitable format without unnecessary bureaucracy.",
            "cta_button_ru": "Оставить заявку", "cta_button_en": "Leave a request",
            "cta_image_alt_ru": "Цветы в вазе и картины с видом на море", "cta_image_alt_en": "Flowers in a vase and paintings of a sea view",
            "adv_title_ru": "Почему с нами удобно работать", "adv_title_en": "Why working with us is easy",
        },
        "images": {"hero_image": "mirame_coop_hero.jpg", "cta_image": "mirame_coop_cta.jpg"},
        "zh": {
            "hero_kicker": "面向室内设计专业人士", "h1": "合作", "hero_subtitle": "诚邀设计师、建筑师和软装师携手合作",
            "hero_lead": "现成的画作，或按您的项目量身创作——为具体的空间而画。", "hero_button": "洽谈项目",
            "hero_image_alt": "明亮的客厅，墙上挂着海景画，窗边有橄榄树",
            "cta_title": "期待长期合作",
            "cta_text": "我们既欢迎单次项目，也欢迎与设计师和工作室的长期合作。如果您有项目，请发给我们，我们会提出合适的合作方式，没有多余的繁琐手续。",
            "cta_button": "提交申请", "cta_image_alt": "花瓶里的花与海景画", "adv_title": "与我们合作为何省心",
        },
        "blocks": [
            {"side": "right", "title_ru": "Вместе создаём особенные интерьеры", "title_en": "Creating special interiors together",
             "text_ru": "Мы любим проекты, в которых картина становится частью замысла, а не случайным дополнением. Подберём готовую работу из каталога или создадим новую под конкретный интерьер — с учётом размеров стены, палитры, сюжета и общего настроения пространства.",
             "text_en": "We love projects where a painting becomes part of the idea rather than a random addition. We will choose a ready work from the catalogue or create a new one for your interior — taking into account the wall size, palette, subject and overall mood of the space.",
             "alt_ru": "Букет белых цветов и кисти в мастерской у мольберта", "alt_en": "A bouquet of white flowers and brushes in the studio by an easel",
             "image": "mirame_coop_project.jpg",
             "zh": {"title": "携手打造独特的室内空间", "text": "我们喜欢这样的项目：画作是设计构思的一部分，而不是随意的点缀。我们可以从目录中为您挑选现成作品，也可以为您的空间专门创作新画——综合考虑墙面尺寸、色调、题材和空间的整体氛围。", "alt": "工作室里画架旁的白色花束和画笔"}},
            {"side": "left", "title_ru": "Гибкий подход к каждому проекту", "title_en": "A flexible approach to every project",
             "text_ru": "Можно изменить размер, пропорции и цветовую гамму, выбрать другую технику или взять понравившуюся работу за отправную точку. Если для квартиры, дома, офиса, ресторана или другого объекта требуется несколько картин, обсудим проект целиком и подберём удобный формат работы.",
             "text_en": "You can change the size, proportions and colour palette, choose a different technique or take a work you like as a starting point. If an apartment, house, office, restaurant or another site needs several paintings, we will discuss the project as a whole and find a convenient way of working.",
             "alt_ru": "Кисти в керамической банке и картина с пионами", "alt_en": "Brushes in a ceramic jar and a painting of peonies",
             "image": "mirame_coop_flexible.jpg",
             "zh": {"title": "灵活应对每一个项目", "text": "可以调整尺寸、比例和色彩，换一种技法，或以您喜欢的作品为起点。如果住宅、办公室、餐厅或其他场所需要多幅画作，我们会整体沟通项目，并选择合适的合作方式。", "alt": "陶罐里的画笔和牡丹画"}},
            {"side": "right", "title_ru": "Просто и удобно работать", "title_en": "Simple and convenient to work with",
             "text_ru": "Вы присылаете интерьер, референсы или техническое задание — мы обсуждаем задачу, согласовываем основные параметры и сроки. Работаем и с готовыми картинами, и с индивидуальными заказами. Доставку организуем через СДЭК или другую согласованную транспортную компанию.",
             "text_en": "You send the interior, references or a brief — we discuss the task and agree the main parameters and timing. We work with both ready-made paintings and individual commissions. We arrange delivery via CDEK or another agreed carrier.",
             "alt_ru": "Книги, чашка и картина с морским видом на деревянном столе", "alt_en": "Books, a cup and a painting of a sea view on a wooden table",
             "image": "mirame_coop_process.jpg",
             "zh": {"title": "简单便捷的合作", "text": "您发来室内照片、参考图或技术要求，我们一起讨论需求，确认主要参数和时间。现成画作和定制订单我们都做。发货通过 CDEK 或另行商定的运输公司安排。", "alt": "木桌上的书、杯子和海景画"}},
        ],
        "advantages": [
            {"icon": "individual", "title_ru": "Индивидуальный подход", "title_en": "Individual approach", "text_ru": "под конкретный интерьер", "text_en": "for your specific interior", "zh": {"title": "个性化服务", "text": "针对具体的室内空间"}},
            {"icon": "flexible", "title_ru": "Гибкие решения", "title_en": "Flexible solutions", "text_ru": "размер, палитра, техника", "text_en": "size, palette, technique", "zh": {"title": "灵活的方案", "text": "尺寸、色调、技法"}},
            {"icon": "brief", "title_ru": "Работаем по ТЗ", "title_en": "We work from a brief", "text_ru": "референсы и готовые проекты", "text_en": "references and ready projects", "zh": {"title": "按技术要求工作", "text": "参考图和现有项目"}},
            {"icon": "delivery", "title_ru": "Надёжная доставка", "title_en": "Reliable delivery", "text_ru": "СДЭК или другая ТК", "text_en": "CDEK or another carrier", "zh": {"title": "可靠的配送", "text": "CDEK 或其他运输公司"}},
            {"icon": "longterm", "title_ru": "Долгосрочное сотрудничество", "title_en": "Long-term cooperation", "text_ru": "для дизайнеров и студий", "text_en": "for designers and studios", "zh": {"title": "长期合作", "text": "面向设计师和工作室"}},
        ],
    },
    "d": {
        "scalars": {
            "hero_mode": "split",
            "hero_kicker_ru": "Для профессионалов интерьера", "hero_kicker_en": "For interior professionals",
            "h1_ru": "Сотрудничество", "h1_en": "Cooperation",
            "hero_subtitle_ru": "Для дизайнеров, архитекторов и специалистов по комплектации интерьеров",
            "hero_subtitle_en": "For designers, architects and interior procurement specialists",
            "hero_lead_ru": "Искусство, которое точно работает в пространстве.", "hero_lead_en": "Art that works precisely in the space.",
            "hero_button_ru": "Обсудить проект", "hero_button_en": "Discuss a project",
            "hero_image_alt_ru": "Мастерская художника: мольберт с картиной, кисти и палитра на деревянном столе",
            "hero_image_alt_en": "An artist’s studio: an easel with a painting, brushes and a palette on a wooden table",
            "cta_title_ru": "Будем рады вашим проектам", "cta_title_en": "We look forward to your projects",
            "cta_text_ru": "Рассматриваем и отдельные задачи, и долгосрочное сотрудничество с профессионалами интерьерной отрасли. Условия по каждому объекту обсуждаются индивидуально — отправьте запрос, и мы предложим подходящий формат работы.",
            "cta_text_en": "We consider both individual tasks and long-term cooperation with interior industry professionals. Terms for each project are discussed individually — send a request and we will offer a suitable way of working.",
            "cta_button_ru": "Оставить заявку", "cta_button_en": "Leave a request",
            "cta_image_alt_ru": "Кисти в глиняной банке и палитра в мастерской", "cta_image_alt_en": "Brushes in a clay jar and a palette in the studio",
            "adv_title_ru": "Наши преимущества", "adv_title_en": "Our advantages",
        },
        "images": {"hero_image": "holstori_coop_hero.jpg", "cta_image": "holstori_coop_cta.jpg"},
        "zh": {
            "hero_kicker": "面向室内设计专业人士", "h1": "合作", "hero_subtitle": "面向设计师、建筑师和室内配置专业人员",
            "hero_lead": "在空间中精准发挥作用的艺术。", "hero_button": "洽谈项目",
            "hero_image_alt": "画家工作室：画架上的画、木桌上的画笔和调色板",
            "cta_title": "期待您的项目",
            "cta_text": "我们既受理单项任务，也欢迎与室内行业专业人士的长期合作。每个项目的条件单独商定——请发送申请，我们会提出合适的合作方式。",
            "cta_button": "提交申请", "cta_image_alt": "工作室里陶罐中的画笔和调色板", "adv_title": "我们的优势",
        },
        "blocks": [
            {"side": "right", "title_ru": "Профессиональный подход к каждому проекту", "title_en": "A professional approach to every project",
             "text_ru": "HolStori работает с дизайнерами интерьера, архитекторами, декораторами и дизайн-студиями. Мы подбираем готовые произведения из каталога или создаём работы по техническому заданию для жилых и коммерческих объектов.",
             "text_en": "HolStori works with interior designers, architects, decorators and design studios. We select ready works from the catalogue or create works to a technical brief for residential and commercial projects.",
             "alt_ru": "Рука художника с кистью у фактурной картины", "alt_en": "An artist’s hand with a brush at a textured painting",
             "image": "holstori_coop_project.jpg",
             "zh": {"title": "对每个项目的专业态度", "text": "HolStori 与室内设计师、建筑师、软装师和设计工作室合作。我们从目录中挑选现成作品，或根据技术要求为住宅和商业项目创作作品。", "alt": "画家手持画笔，靠近肌理画作"}},
            {"side": "left", "title_ru": "Гибкость и свобода в реализации", "title_en": "Flexibility and freedom in execution",
             "text_ru": "В проекте можно учитывать необходимые размеры, пропорции, цветовую гамму, стилистику и технику исполнения. При необходимости несколько работ разрабатываются как единая серия, чтобы искусство точно поддерживало концепцию помещения.",
             "text_en": "A project can take into account the required sizes, proportions, colour palette, style and technique. When needed, several works are developed as a single series, so that the art supports the concept of the space precisely.",
             "alt_ru": "Кисти, палитра и картина в раме на столе мастерской", "alt_en": "Brushes, a palette and a framed painting on a studio table",
             "image": "holstori_coop_flexible.jpg",
             "zh": {"title": "实现上的灵活与自由", "text": "项目可以考虑所需的尺寸、比例、色调、风格和技法。必要时，几件作品会作为一个系列来创作，使艺术准确地呼应空间的整体构思。", "alt": "工作室桌上的画笔、调色板和装框画作"}},
            {"side": "right", "title_ru": "Удобное сотрудничество", "title_en": "Convenient cooperation",
             "text_ru": "Для старта достаточно описания проекта, изображений интерьера, размеров и визуальных ориентиров. После этого согласовываются вариант исполнения, параметры и сроки. Доставка — через СДЭК или выбранную транспортную компанию.",
             "text_en": "To start, a description of the project, interior images, dimensions and visual references are enough. After that the execution option, parameters and timing are agreed. Delivery is via CDEK or a chosen carrier.",
             "alt_ru": "Деревянный стол с керамикой, книгами и картинами в интерьере", "alt_en": "A wooden table with ceramics, books and paintings in an interior",
             "image": "holstori_coop_process.jpg",
             "zh": {"title": "便捷的合作", "text": "开始时，只需项目说明、室内照片、尺寸和视觉参考。之后再确认实现方案、参数和时间。发货通过 CDEK 或选定的运输公司。", "alt": "室内的木桌，摆着陶器、书和画作"}},
        ],
        "advantages": [
            {"icon": "individual", "title_ru": "Индивидуальные решения", "title_en": "Individual solutions", "text_ru": "под конкретный объект", "text_en": "for a specific project", "zh": {"title": "个性化方案", "text": "针对具体项目"}},
            {"icon": "flexible", "title_ru": "Гибкость размеров и палитры", "title_en": "Flexible sizes and palette", "text_ru": "под требования проекта", "text_en": "to project requirements", "zh": {"title": "尺寸与色调灵活", "text": "符合项目要求"}},
            {"icon": "brief", "title_ru": "Работа по ТЗ", "title_en": "Work to a brief", "text_ru": "с профессиональными командами", "text_en": "with professional teams", "zh": {"title": "按技术要求工作", "text": "与专业团队合作"}},
            {"icon": "delivery", "title_ru": "Доставка по России и за рубеж", "title_en": "Delivery in Russia and abroad", "text_ru": "по согласованной схеме", "text_en": "on an agreed scheme", "zh": {"title": "俄罗斯境内及境外配送", "text": "按商定方案"}},
            {"icon": "longterm", "title_ru": "Долгосрочное партнёрство", "title_en": "Long-term partnership", "text_ru": "для дизайнеров и студий", "text_en": "for designers and studios", "zh": {"title": "长期合作伙伴关系", "text": "面向设计师和工作室"}},
        ],
    },
}
