"""Стартовое содержимое страницы «Сотрудничество» для МираМе (A) и ХолСтори (D): RU, EN, 中文.

Тексты, порядок блоков, фото и пиктограммы — по финальным эталонам (EXACT_REFERENCE) каждого сайта.
Сайты наполняются независимо: свои фото, свои тексты, свои настройки.
"""

PAGE = {
    "a": {
        "title_ru": "Сотрудничество", "title_en": "Cooperation", "nav_title_ru": "Сотрудничество", "nav_title_en": "Cooperation",
        "slug_ru": "сотрудничество", "slug_en": "cooperation",
        "seo_title_ru": "Сотрудничество с дизайнерами и архитекторами", "seo_title_en": "Cooperation with designers and architects",
        "seo_description_ru": "Приглашаем дизайнеров, архитекторов и декораторов: готовые картины и работы по вашему проекту — под конкретное пространство, стиль и задачу.",
        "seo_description_en": "We invite designers, architects and decorators: ready-made paintings and works for your project — made for a specific space, style and task.",
        "zh": {"title": "合作", "nav_title": "合作", "seo_title": "与设计师和建筑师合作",
               "seo_description": "诚邀设计师、建筑师和软装师：现成的画作，或按您的项目创作的作品——适合具体的空间、风格和需求。"},
    },
    "d": {
        "title_ru": "Сотрудничество", "title_en": "Cooperation", "nav_title_ru": "Сотрудничество", "nav_title_en": "Cooperation",
        "slug_ru": "сотрудничество", "slug_en": "cooperation",
        "seo_title_ru": "Сотрудничество с дизайнерами, архитекторами и комплектаторами", "seo_title_en": "Cooperation with designers, architects and procurement specialists",
        "seo_description_ru": "HolStori приглашает к сотрудничеству дизайнеров интерьера, архитекторов, декораторов и студии: готовые работы и картины по вашему техническому заданию.",
        "seo_description_en": "HolStori invites interior designers, architects, decorators and studios to work with us: ready works and paintings to your technical brief.",
        "zh": {"title": "合作", "nav_title": "合作", "seo_title": "与设计师、建筑师和室内配置专业人员合作",
               "seo_description": "HolStori 诚邀室内设计师、建筑师、软装师和工作室合作：现成作品，以及按您的技术要求创作的画作。"},
    },
}

CONTENT = {
    "a": {
        "scalars": {
            "hero_mode": "split", "hero_focus_x": 50, "hero_focus_y": 50,
            "hero_kicker_ru": "Для профессионалов интерьера", "hero_kicker_en": "For interior professionals",
            "h1_ru": "Сотрудничество", "h1_en": "Cooperation",
            "hero_subtitle_ru": "Приглашаем дизайнеров, архитекторов и декораторов",
            "hero_subtitle_en": "We invite designers, architects and decorators",
            "hero_lead_ru": "Готовые картины и работы по вашему проекту — под конкретное пространство, стиль и задачу.",
            "hero_lead_en": "Ready-made paintings and works for your project — made for a specific space, style and task.",
            "hero_button_ru": "Обсудить проект", "hero_button_en": "Discuss a project",
            "hero_image_alt_ru": "Светлая гостиная с картиной с морским видом на стене, растениями и мягким диваном",
            "hero_image_alt_en": "A bright living room with a seascape painting on the wall, plants and a soft sofa",
            "cta_title_ru": "У вас есть проект?", "cta_title_en": "Have a project?",
            "cta_text_ru": "Давайте обсудим его. Мы предложим подходящий формат работы.",
            "cta_text_en": "Let’s discuss it. We will offer a suitable way of working.",
            "cta_button_ru": "Оставить заявку", "cta_button_en": "Leave a request",
            "adv_title_ru": "Почему с нами удобно работать", "adv_title_en": "Why working with us is easy",
        },
        "images": {"hero_image": "mirame_coop_hero.jpg"},
        "zh": {
            "hero_kicker": "面向室内设计专业人士", "h1": "合作", "hero_subtitle": "诚邀设计师、建筑师和软装师",
            "hero_lead": "现成的画作，或按您的项目创作的作品——适合具体的空间、风格和需求。", "hero_button": "洽谈项目",
            "hero_image_alt": "明亮的客厅，墙上挂着海景画，摆有植物和柔软的沙发",
            "cta_title": "您有项目吗？", "cta_text": "让我们一起讨论。我们会提出合适的合作方式。", "cta_button": "提交申请",
            "adv_title": "与我们合作为何省心",
        },
        "blocks": [
            {"side": "left", "focus_y": 38, "title_ru": "Вместе создаём особенные интерьеры", "title_en": "Creating special interiors together",
             "text_ru": "Мы любим проекты, в которых картина становится частью замысла, а не случайным дополнением. Подберём готовую работу из каталога или создадим новую под конкретный интерьер — с учётом размеров стены, палитры, сюжета и общего настроения пространства.",
             "text_en": "We love projects where a painting becomes part of the idea rather than a random addition. We will choose a ready work from the catalogue or create a new one for your interior — taking into account the wall size, palette, subject and overall mood of the space.",
             "alt_ru": "Кисти в керамической банке и картина с пионами на рабочем столе", "alt_en": "Brushes in a ceramic jar and a painting of peonies on a work table",
             "image": "mirame_coop_block1.jpg",
             "zh": {"title": "携手打造独特的室内空间", "text": "我们喜欢这样的项目：画作是设计构思的一部分，而不是随意的点缀。我们可以从目录中为您挑选现成作品，也可以为您的空间专门创作新画——综合考虑墙面尺寸、色调、题材和空间的整体氛围。", "alt": "工作台上陶罐里的画笔和牡丹画"}},
            {"side": "right", "focus_y": 45, "title_ru": "Гибкий подход к каждому проекту", "title_en": "A flexible approach to every project",
             "text_ru": "Можно изменить размер, пропорции, палитру, подобрать другую технику или взять понравившуюся работу за отправную точку и создать новый вариант. Работаем как с частными, так и с коммерческими проектами: квартиры, дома, офисы, рестораны, отели и общественные пространства.",
             "text_en": "You can change the size, proportions and palette, choose a different technique or take a work you like as a starting point and create a new version. We work with both private and commercial projects: apartments, houses, offices, restaurants, hotels and public spaces.",
             "alt_ru": "Стол с цветами, книгами и картиной с морским видом", "alt_en": "A table with flowers, books and a painting of a sea view",
             "image": "mirame_coop_block2.jpg",
             "zh": {"title": "灵活应对每一个项目", "text": "可以调整尺寸、比例和色调，选择其他技法，或以您喜欢的作品为起点创作新的版本。我们既与私人客户合作，也承接商业项目：公寓、住宅、办公室、餐厅、酒店和公共空间。", "alt": "摆着花、书和海景画的桌子"}},
        ],
        "advantages": [
            {"icon": "individual", "title_ru": "Индивидуальный подход", "title_en": "Individual approach", "zh": {"title": "个性化服务"}},
            {"icon": "flexible", "title_ru": "Гибкие решения", "title_en": "Flexible solutions", "zh": {"title": "灵活的方案"}},
            {"icon": "brief", "title_ru": "Работаем по ТЗ", "title_en": "We work from a brief", "zh": {"title": "按技术要求工作"}},
            {"icon": "delivery", "title_ru": "Надёжная доставка", "title_en": "Reliable delivery", "zh": {"title": "可靠的配送"}},
            {"icon": "partner", "title_ru": "Долгосрочное сотрудничество", "title_en": "Long-term cooperation", "zh": {"title": "长期合作"}},
        ],
        # Дополнительный визуал: на странице по умолчанию скрыт, лежит в медиатеке для замены любого фото.
        "library": [{"title": "Сотрудничество — дополнительный визуал", "image": "mirame_coop_optional.jpg",
                     "alt_ru": "Светлая студия с картиной с морским видом и оливковым деревом", "alt_en": "A bright studio with a seascape painting and an olive tree"}],
    },
    "d": {
        "scalars": {
            "hero_mode": "split", "hero_focus_x": 50, "hero_focus_y": 50,
            "hero_kicker_ru": "Для профессионалов", "hero_kicker_en": "For professionals",
            "h1_ru": "Сотрудничество", "h1_en": "Cooperation",
            "hero_subtitle_ru": "Для дизайнеров, архитекторов и специалистов по комплектации интерьеров",
            "hero_subtitle_en": "For designers, architects and interior procurement specialists",
            "hero_lead_ru": "", "hero_lead_en": "",
            "hero_button_ru": "Обсудить проект", "hero_button_en": "Discuss a project",
            "hero_image_alt_ru": "Мастерская художника: большая картина на стене, окно и рабочий стол с кистями",
            "hero_image_alt_en": "An artist’s studio: a large painting on the wall, a window and a work table with brushes",
            "cta_title_ru": "Обсудим ваш проект?", "cta_title_en": "Shall we discuss your project?",
            "cta_text_ru": "Отправьте описание, изображения интерьера или **техническое задание** — мы предложим **оптимальный формат работы.**",
            "cta_text_en": "Send a description, interior images or a **technical brief** — we will offer **the best way of working.**",
            "cta_button_ru": "Оставить заявку", "cta_button_en": "Leave a request",
            "cta_image_alt_ru": "", "cta_image_alt_en": "", "cta_focus_x": 50, "cta_focus_y": 50,
            "adv_title_ru": "Почему с нами удобно работать", "adv_title_en": "Why working with us is easy",
        },
        "images": {"hero_image": "holstori_coop_hero.jpg", "cta_image": "holstori_coop_cta.jpg"},
        "zh": {
            "hero_kicker": "面向专业人士", "h1": "合作", "hero_subtitle": "面向设计师、建筑师和室内配置专业人员", "hero_button": "洽谈项目",
            "hero_image_alt": "画家工作室：墙上的大幅画作、窗户和摆着画笔的工作台",
            "cta_title": "我们来谈谈您的项目？", "cta_text": "请发送说明、室内照片或**技术要求**——我们会提出**最合适的合作方式。**", "cta_button": "提交申请",
            "adv_title": "与我们合作为何省心",
        },
        "blocks": [
            {"side": "left", "focus_y": 50, "title_ru": "Профессиональный подход к каждому проекту", "title_en": "A professional approach to every project",
             "text_ru": "HolStori приглашает к сотрудничеству дизайнеров интерьера, архитекторов, декораторов и студии. Мы подберём готовые работы из каталога или создадим картину по вашему техническому заданию — с учётом размеров, цветовой гаммы, стилистики и особенностей пространства.",
             "text_en": "HolStori invites interior designers, architects, decorators and studios to work with us. We will select ready works from the catalogue or create a painting to your technical brief — taking into account the size, colour palette, style and character of the space.",
             "alt_ru": "Угол мастерской: кисти в банке, рамы и сухоцветы в мягком свете", "alt_en": "A corner of the studio: brushes in a jar, frames and dried flowers in soft light",
             "image": "holstori_coop_block1.jpg",
             "zh": {"title": "对每个项目的专业态度", "text": "HolStori 诚邀室内设计师、建筑师、软装师和工作室合作。我们会从目录中挑选现成作品，或根据您的技术要求创作画作——综合考虑尺寸、色调、风格和空间特点。", "alt": "工作室一角：罐中的画笔、画框和干花，柔和的光线"}},
            {"side": "right", "focus_y": 55, "title_ru": "Гибкость и свобода в реализации", "title_en": "Flexibility and freedom in execution",
             "text_ru": "Формат работы позволяет учитывать необходимые размеры, пропорции, цветовую гамму и технику исполнения. Можно разработать несколько работ в рамках одного объекта. Работаем с жилыми и коммерческими проектами: квартиры, дома, офисы, рестораны, отели, общественные пространства.",
             "text_en": "The way of working allows for the required sizes, proportions, colour palette and technique. Several works can be developed for a single project. We work with residential and commercial projects: apartments, houses, offices, restaurants, hotels and public spaces.",
             "alt_ru": "Кисти, палитра с красками и картина в раме на столе мастерской", "alt_en": "Brushes, a palette with paints and a framed painting on a studio table",
             "image": "holstori_coop_block2.jpg",
             "zh": {"title": "实现上的灵活与自由", "text": "合作方式可以兼顾所需的尺寸、比例、色调和技法。可以为同一个项目创作多幅作品。我们承接住宅和商业项目：公寓、住宅、办公室、餐厅、酒店和公共空间。", "alt": "工作室桌上的画笔、调色板和装框画作"}},
        ],
        "advantages": [
            {"icon": "individual", "title_ru": "Индивидуальный подход", "title_en": "Individual approach", "zh": {"title": "个性化服务"}},
            {"icon": "flexible", "title_ru": "Гибкость в реализации", "title_en": "Flexibility in execution", "zh": {"title": "实现上的灵活"}},
            {"icon": "brief", "title_ru": "Работаем по ТЗ и с готовыми проектами", "title_en": "We work to a brief and with ready projects", "zh": {"title": "按技术要求及现有项目工作"}},
            {"icon": "delivery", "title_ru": "Доставка по России и за рубеж", "title_en": "Delivery in Russia and abroad", "zh": {"title": "俄罗斯境内及境外配送"}},
            {"icon": "partner", "title_ru": "Надёжное партнёрство", "title_en": "A reliable partnership", "zh": {"title": "可靠的合作伙伴关系"}},
        ],
        "library": [{"title": "Сотрудничество — дополнительный визуал", "image": "holstori_coop_optional.jpg",
                     "alt_ru": "Мастерская художника: мольберт, рабочий стол и кисти", "alt_en": "An artist’s studio: an easel, a work table and brushes"}],
    },
}
