"""Городские страницы сайта D «ХолСтори» — деловой, спокойный тон (ТЗ 9.1).

Каждый текст написан для своего города. Адреса и координаты не заполнены: владелец вносит
реальные данные в админке («Города — страницы»), после этого на странице появляется карта.
"""

PAGE = {
    "kind": "cities", "slug_ru": "города", "slug_en": "cities",
    "title_ru": "Картины с доставкой по городам", "title_en": "Paintings delivered to your city",
    "nav_title_ru": "Города", "nav_title_en": "Cities",
    "kicker_ru": "География работы", "kicker_en": "Where we work",
    "intro_ru": "Сведения о получении картин в основных городах: условия доставки, контакты и работы из каталога. Обращения из других населенных пунктов принимаются на общих условиях.",
    "intro_en": "Information on receiving paintings in major cities: delivery terms, contacts and works from the catalogue. Requests from other locations are accepted on the general terms.",
    "empty_ru": "Городские страницы будут опубликованы после заполнения данных.",
    "empty_en": "City pages will be published once the data is filled in.",
    "cta_text_ru": "Город не указан в списке? Доставка согласуется индивидуально", "cta_text_en": "City not listed? Delivery is arranged individually",
    "cta_button_ru": "Согласовать доставку", "cta_button_en": "Arrange delivery",
    "seo_title_ru": "Картины с доставкой по городам России", "seo_title_en": "Paintings delivered across Russia",
    "seo_description_ru": "Готовые картины и индивидуальные заказы с доставкой в Москву, Санкт-Петербург, Новосибирск и другие города. Условия получения и контакты по городам.",
    "seo_description_en": "Ready paintings and custom commissions delivered to Moscow, Saint Petersburg, Novosibirsk and other cities. Delivery terms and contacts by city.",
}

DELIVERY_RU = "Доставка {to} выполняется через СДЭК или другую транспортную компанию по согласованию с Заказчиком. Получение — в пункте выдачи или курьером. Стоимость доставки оплачивается отдельно; упаковка, маршрут и срок согласуются до отправки."
DELIVERY_EN = "Delivery to {name} is made via CDEK or another carrier agreed with the customer. Receipt at a pick-up point or by courier. Delivery is paid separately; packing, route and timing are agreed before shipping."

CITIES = [
    {"source_id": "524901", "name_ru": "Москва", "name_en": "Moscow", "name_in_ru": "в Москве", "to": "в Москву",
     "title_ru": "Картины в Москве", "title_en": "Paintings in Moscow",
     "intro_ru": "Готовые работы и индивидуальные заказы для жилых и коммерческих интерьеров Москвы.",
     "intro_en": "Ready works and custom commissions for residential and commercial interiors in Moscow.",
     "body_ru": "## Подбор под интерьер\nДля столичных объектов часто требуется работа под конкретную задачу: размер под стену, цветовое решение под отделку, серия для офиса или гостиничного номера. Эти параметры фиксируются в заявке и согласуются до начала исполнения.\n\n## Порядок обращения\nВыберите работу в каталоге или опишите задачу. Для индивидуального заказа достаточно указать размер, сюжет и желаемый срок получения; фото помещения ускоряет согласование.",
     "body_en": "## Selection for the interior\nProjects in Moscow often need a work for a specific task: a size for the wall, a colour scheme for the finish, a series for an office or hotel room. These parameters are recorded in the request and agreed before work begins.",
     "seo_title_ru": "Картины в Москве — готовые и на заказ", "seo_title_en": "Paintings in Moscow",
     "seo_description_ru": "Картины в Москве: готовые произведения и индивидуальные заказы для жилых и коммерческих интерьеров. Доставка через СДЭК или другую ТК по согласованию."},
    {"source_id": "498817", "name_ru": "Санкт-Петербург", "name_en": "Saint Petersburg", "name_in_ru": "в Санкт-Петербурге", "to": "в Санкт-Петербург",
     "title_ru": "Картины в Санкт-Петербурге", "title_en": "Paintings in Saint Petersburg",
     "intro_ru": "Каталог картин и индивидуальные заказы с доставкой в Санкт-Петербург.",
     "intro_en": "Painting catalogue and custom commissions with delivery to Saint Petersburg.",
     "body_ru": "## Интерьеры исторического центра и новых районов\nВ помещениях с высокими потолками востребованы крупные форматы и вертикальные композиции; для современных квартир — светлые пейзажи и абстракция. При заказе учитываются освещение помещения и высота размещения.\n\n## Согласование\nПараметры новой работы — размер, цветовое решение, сюжет — фиксируются в обращении. Возможность исполнения, стоимость и сроки подтверждаются до начала работы.",
     "body_en": "## Historic centre and new districts\nRooms with high ceilings call for large formats and vertical compositions; modern flats suit bright landscapes and abstraction. Lighting and hanging height are taken into account.",
     "seo_title_ru": "Картины в Санкт-Петербурге", "seo_title_en": "Paintings in Saint Petersburg",
     "seo_description_ru": "Картины в Санкт-Петербурге: каталог готовых работ и индивидуальные заказы под интерьер. Доставка через СДЭК или другую ТК, оплата доставки отдельно."},
    {"source_id": "1496747", "name_ru": "Новосибирск", "name_en": "Novosibirsk", "name_in_ru": "в Новосибирске", "to": "в Новосибирск",
     "title_ru": "Картины в Новосибирске", "title_en": "Paintings in Novosibirsk",
     "intro_ru": "Готовые картины и работы на заказ с получением в Новосибирске.",
     "intro_en": "Ready paintings and commissioned works for receipt in Novosibirsk.",
     "body_ru": "## Выбор работы\nВ каталоге представлены пейзажи, абстракция, цветочные и фигуративные сюжеты. Для каждой работы указаны статус и известные характеристики; параметры, отсутствующие в карточке, уточняются по запросу.\n\n## Отправка в зимний период\nПри перевозке в холодное время года упаковка подбирается с учетом температурного режима. Условия согласуются до передачи работы перевозчику.",
     "body_en": "## Choosing a work\nThe catalogue includes landscapes, abstraction, floral and figurative subjects. Status and known characteristics are listed for each work.\n\n## Winter shipping\nPacking for cold-season transport is chosen with temperature in mind.",
     "seo_title_ru": "Картины в Новосибирске", "seo_title_en": "Paintings in Novosibirsk",
     "seo_description_ru": "Картины в Новосибирске: готовые работы и индивидуальные заказы. Упаковка с учетом сезона, доставка через СДЭК или другую ТК по согласованию."},
    {"source_id": "1486209", "name_ru": "Екатеринбург", "name_en": "Yekaterinburg", "name_in_ru": "в Екатеринбурге", "to": "в Екатеринбург",
     "title_ru": "Картины в Екатеринбурге", "title_en": "Paintings in Yekaterinburg",
     "intro_ru": "Картины для квартир, офисов и общественных пространств Екатеринбурга.",
     "intro_en": "Paintings for flats, offices and public spaces in Yekaterinburg.",
     "body_ru": "## Коммерческие и жилые объекты\nДля офисов и общественных пространств доступен подбор серии работ в едином стиле; для жилых интерьеров — отдельные произведения или парные композиции. Состав заказа и размеры согласуются по заявке.\n\n## Документы по заказу\nПараметры работы, стоимость, срок исполнения и условия доставки фиксируются при согласовании заказа.",
     "body_en": "## Commercial and residential projects\nFor offices and public spaces a series of works in one style can be selected; for homes — single works or pairs. Composition and sizes are agreed on request.",
     "seo_title_ru": "Картины в Екатеринбурге", "seo_title_en": "Paintings in Yekaterinburg",
     "seo_description_ru": "Картины в Екатеринбурге для квартир и офисов: готовые произведения, серии и индивидуальные заказы. Доставка через СДЭК или другую ТК."},
    {"source_id": "551487", "name_ru": "Казань", "name_en": "Kazan", "name_in_ru": "в Казани", "to": "в Казань",
     "title_ru": "Картины в Казани", "title_en": "Paintings in Kazan",
     "intro_ru": "Готовые работы и индивидуальные заказы с доставкой в Казань.",
     "intro_en": "Ready works and custom commissions with delivery to Kazan.",
     "body_ru": "## Сюжеты и техники\nКаталог включает пейзажи, морские сюжеты, абстракцию и работы в технике жидкого акрила. Для индивидуального заказа можно указать сюжет, цветовую гамму и формат.\n\n## Порядок работы\nОбращение, согласование параметров и стоимости, исполнение, подготовка к отправке и передача перевозчику. Дата получения указывается отдельно от даты готовности.",
     "body_en": "## Subjects and techniques\nThe catalogue includes landscapes, seascapes, abstraction and fluid acrylic works. For a commission you can specify subject, palette and format.",
     "seo_title_ru": "Картины в Казани", "seo_title_en": "Paintings in Kazan",
     "seo_description_ru": "Картины в Казани: пейзажи, абстракция, жидкий акрил и индивидуальные заказы. Доставка через СДЭК или другую ТК, оплата доставки отдельно."},
    {"source_id": "1502026", "name_ru": "Красноярск", "name_en": "Krasnoyarsk", "name_in_ru": "в Красноярске", "to": "в Красноярск",
     "title_ru": "Картины в Красноярске", "title_en": "Paintings in Krasnoyarsk",
     "intro_ru": "Каталог картин и заказ работ с доставкой в Красноярск.",
     "intro_en": "Painting catalogue and commissions with delivery to Krasnoyarsk.",
     "body_ru": "## Дальние отправки\nПри значительном расстоянии особое внимание уделяется упаковке: учитываются размер, основа, наличие рамы и условия перевозки. Требования к упаковке согласуются до отправки.\n\n## Выбор и заказ\nВыберите работу в каталоге или направьте описание задачи. Для работы по мотивам проданного произведения сохраняется ссылка на исходный пример.",
     "body_en": "## Long-distance shipping\nOver long distances packing gets special attention: size, support, frame and transport conditions are taken into account.",
     "seo_title_ru": "Картины в Красноярске", "seo_title_en": "Paintings in Krasnoyarsk",
     "seo_description_ru": "Картины в Красноярске: готовые работы и индивидуальные заказы. Надежная упаковка для дальней перевозки, доставка через СДЭК или другую ТК."},
    {"source_id": "520555", "name_ru": "Нижний Новгород", "name_en": "Nizhny Novgorod", "name_in_ru": "в Нижнем Новгороде", "to": "в Нижний Новгород",
     "title_ru": "Картины в Нижнем Новгороде", "title_en": "Paintings in Nizhny Novgorod",
     "intro_ru": "Готовые произведения и индивидуальные заказы для интерьеров Нижнего Новгорода.",
     "intro_en": "Ready works and custom commissions for interiors in Nizhny Novgorod.",
     "body_ru": "## Форматы\nДля широких стен подходят панорамные форматы 30 × 60, 40 × 80 и 50 × 100 см; для компактных помещений — квадратные и небольшие прямоугольные. Полный перечень стандартных размеров доступен в форме заказа, возможен индивидуальный размер.\n\n## Согласование\nРазмер, цветовое решение и срок фиксируются в заявке и подтверждаются до начала работы.",
     "body_en": "## Formats\nPanoramic formats 30 × 60, 40 × 80 and 50 × 100 cm suit wide walls; square and small rectangular ones suit compact rooms. A custom size is possible.",
     "seo_title_ru": "Картины в Нижнем Новгороде", "seo_title_en": "Paintings in Nizhny Novgorod",
     "seo_description_ru": "Картины в Нижнем Новгороде: панорамные и стандартные форматы, индивидуальные размеры. Доставка через СДЭК или другую ТК по согласованию."},
    {"source_id": "1508291", "name_ru": "Челябинск", "name_en": "Chelyabinsk", "name_in_ru": "в Челябинске", "to": "в Челябинск",
     "title_ru": "Картины в Челябинске", "title_en": "Paintings in Chelyabinsk",
     "intro_ru": "Картины с доставкой в Челябинск: каталог и индивидуальные заказы.",
     "intro_en": "Paintings delivered to Chelyabinsk: catalogue and custom commissions.",
     "body_ru": "## Для жилых и рабочих помещений\nВ каталоге есть спокойные пейзажи для жилых комнат и выразительная абстракция для кабинетов и переговорных. Для рабочих пространств возможен подбор нескольких работ в едином колорите.\n\n## Заявка\nДостаточно имени и одного контакта. Город, размер, срок и пример можно добавить в той же форме.",
     "body_en": "## For homes and workplaces\nCalm landscapes for living rooms and expressive abstraction for studies and meeting rooms. Several works in one palette can be selected for workspaces.",
     "seo_title_ru": "Картины в Челябинске", "seo_title_en": "Paintings in Chelyabinsk",
     "seo_description_ru": "Картины в Челябинске для дома и офиса: пейзажи, абстракция, индивидуальные заказы. Доставка через СДЭК или другую ТК, оплата отдельно."},
    {"source_id": "479561", "name_ru": "Уфа", "name_en": "Ufa", "name_in_ru": "в Уфе", "to": "в Уфу",
     "title_ru": "Картины в Уфе", "title_en": "Paintings in Ufa",
     "intro_ru": "Готовые картины и работы на заказ с доставкой в Уфу.",
     "intro_en": "Ready paintings and commissioned works delivered to Ufa.",
     "body_ru": "## Каталог\nПейзажи, цветочные сюжеты, натюрморты и абстракция. Статус каждой работы — в наличии, под заказ или продана — указан в карточке.\n\n## Работа по мотивам\nЕсли понравившаяся работа продана, доступен заказ новой картины по ее мотивам. Параметры, стоимость и срок нового исполнения согласуются отдельно.",
     "body_en": "## Catalogue\nLandscapes, floral subjects, still lifes and abstraction. The status of each work is shown on its card.\n\n## Inspired by a sold work\nIf a work is sold, a new painting inspired by it can be commissioned.",
     "seo_title_ru": "Картины в Уфе", "seo_title_en": "Paintings in Ufa",
     "seo_description_ru": "Картины в Уфе: пейзажи, цветы, натюрморты, абстракция и заказ по мотивам проданных работ. Доставка через СДЭК или другую ТК."},
    {"source_id": "499099", "name_ru": "Самара", "name_en": "Samara", "name_in_ru": "в Самаре", "to": "в Самару",
     "title_ru": "Картины в Самаре", "title_en": "Paintings in Samara",
     "intro_ru": "Каталог картин и индивидуальные заказы с доставкой в Самару.",
     "intro_en": "Painting catalogue and custom commissions delivered to Samara.",
     "body_ru": "## Морские и речные сюжеты\nВ каталоге представлены морские пейзажи и работы с водной тематикой. Для индивидуального заказа можно указать характер освещения, время суток и цветовую гамму.\n\n## Размеры\nФактический размер готовой работы указан в карточке. Для новой картины выбирается стандартный формат или задаются собственные ширина и высота.",
     "body_en": "## Sea and river subjects\nThe catalogue includes seascapes and water-themed works. For a commission you can specify lighting, time of day and palette.",
     "seo_title_ru": "Картины в Самаре", "seo_title_en": "Paintings in Samara",
     "seo_description_ru": "Картины в Самаре: морские пейзажи, работы с водной тематикой, индивидуальные размеры. Доставка через СДЭК или другую ТК по согласованию."},
    {"source_id": "501175", "name_ru": "Ростов-на-Дону", "name_en": "Rostov-on-Don", "name_in_ru": "в Ростове-на-Дону", "to": "в Ростов-на-Дону",
     "title_ru": "Картины в Ростове-на-Дону", "title_en": "Paintings in Rostov-on-Don",
     "intro_ru": "Готовые работы и индивидуальные заказы для интерьеров Ростова-на-Дону.",
     "intro_en": "Ready works and custom commissions for interiors in Rostov-on-Don.",
     "body_ru": "## Цветовые решения\nДля светлых помещений с большим количеством солнца подходят как насыщенные теплые сюжеты, так и прохладные морские тона. Цветовое решение новой работы согласуется с учетом отделки и освещения.\n\n## Порядок\nЗаявка, согласование параметров, исполнение, подготовка к отправке. Стоимость доставки не входит в стоимость картины.",
     "body_en": "## Colour schemes\nBright sunny rooms suit both rich warm subjects and cool sea tones. The colour scheme of a new work is agreed with the finish and lighting in mind.",
     "seo_title_ru": "Картины в Ростове-на-Дону", "seo_title_en": "Paintings in Rostov-on-Don",
     "seo_description_ru": "Картины в Ростове-на-Дону: готовые работы и заказ с подбором цветового решения под интерьер. Доставка через СДЭК или другую ТК."},
    {"source_id": "542420", "name_ru": "Краснодар", "name_en": "Krasnodar", "name_in_ru": "в Краснодаре", "to": "в Краснодар",
     "title_ru": "Картины в Краснодаре", "title_en": "Paintings in Krasnodar",
     "intro_ru": "Картины для новых квартир и коммерческих помещений Краснодара.",
     "intro_en": "Paintings for new flats and commercial premises in Krasnodar.",
     "body_ru": "## Для новых интерьеров\nВ новых квартирах со светлой отделкой картина становится основным акцентом. Возможен подбор крупного формата или серии для нескольких помещений.\n\n## Коммерческие помещения\nДля кафе, салонов и офисов работы подбираются по стилю пространства; количество и размеры фиксируются в заявке.",
     "body_en": "## For new interiors\nIn new flats with light finishes a painting becomes the main accent. A large format or a series for several rooms can be selected.",
     "seo_title_ru": "Картины в Краснодаре", "seo_title_en": "Paintings in Krasnodar",
     "seo_description_ru": "Картины в Краснодаре для новых квартир, кафе и офисов: готовые работы, серии и индивидуальные заказы. Доставка через СДЭК или другую ТК."},
    {"source_id": "1496153", "name_ru": "Омск", "name_en": "Omsk", "name_in_ru": "в Омске", "to": "в Омск",
     "title_ru": "Картины в Омске", "title_en": "Paintings in Omsk",
     "intro_ru": "Готовые картины и индивидуальные заказы с доставкой в Омск.",
     "intro_en": "Ready paintings and custom commissions delivered to Omsk.",
     "body_ru": "## Пейзажная живопись\nВ каталоге представлены пейзажи с открытым горизонтом, лесные и полевые сюжеты. Для заказа можно указать время года и характер освещения.\n\n## Получение\nКартина передается транспортной компании после согласования упаковки и маршрута. Срок перевозки указывается отдельно от срока исполнения.",
     "body_en": "## Landscape painting\nLandscapes with open horizons, forest and field subjects. For a commission you can specify the season and lighting.",
     "seo_title_ru": "Картины в Омске", "seo_title_en": "Paintings in Omsk",
     "seo_description_ru": "Картины в Омске: пейзажи, лесные и полевые сюжеты, индивидуальные заказы. Доставка через СДЭК или другую ТК, оплата доставки отдельно."},
    {"source_id": "472045", "name_ru": "Воронеж", "name_en": "Voronezh", "name_in_ru": "в Воронеже", "to": "в Воронеж",
     "title_ru": "Картины в Воронеже", "title_en": "Paintings in Voronezh",
     "intro_ru": "Каталог картин и работы на заказ с доставкой в Воронеж.",
     "intro_en": "Painting catalogue and commissions delivered to Voronezh.",
     "body_ru": "## Сюжеты\nМорские и летние пейзажи, цветочные композиции, натюрморты. Для каждой работы указаны статус и известные характеристики.\n\n## Индивидуальный заказ\nПередайте пожелания к сюжету, цвету, размеру и оформлению. Возможность исполнения, стоимость и сроки согласуются до начала работы.",
     "body_en": "## Subjects\nSea and summer landscapes, floral compositions, still lifes. Status and known characteristics are listed for each work.",
     "seo_title_ru": "Картины в Воронеже", "seo_title_en": "Paintings in Voronezh",
     "seo_description_ru": "Картины в Воронеже: морские и летние пейзажи, цветы, натюрморты и индивидуальные заказы. Доставка через СДЭК или другую ТК."},
    {"source_id": "511196", "name_ru": "Пермь", "name_en": "Perm", "name_in_ru": "в Перми", "to": "в Пермь",
     "title_ru": "Картины в Перми", "title_en": "Paintings in Perm",
     "intro_ru": "Готовые произведения и индивидуальные заказы с доставкой в Пермь.",
     "intro_en": "Ready works and custom commissions delivered to Perm.",
     "body_ru": "## Техники исполнения\nМасло, акрил, жидкий акрил, фактурные работы. Техника указывается в характеристиках каждой работы и не заменяет жанр.\n\n## Современная абстракция\nРаботы в технике жидкого акрила подходят для современных интерьеров. Для заказа можно указать цветовую гамму и формат.",
     "body_en": "## Techniques\nOil, acrylic, fluid acrylic, textured works. The technique is listed in each work’s characteristics.",
     "seo_title_ru": "Картины в Перми", "seo_title_en": "Paintings in Perm",
     "seo_description_ru": "Картины в Перми: масло, акрил, жидкий акрил и фактурные работы, индивидуальные заказы. Доставка через СДЭК или другую ТК."},
    {"source_id": "472757", "name_ru": "Волгоград", "name_en": "Volgograd", "name_in_ru": "в Волгограде", "to": "в Волгоград",
     "title_ru": "Картины в Волгограде", "title_en": "Paintings in Volgograd",
     "intro_ru": "Картины с доставкой в Волгоград: готовые работы и заказы.",
     "intro_en": "Paintings delivered to Volgograd: ready works and commissions.",
     "body_ru": "## Панорамные форматы\nДля протяженных стен предлагаются панорамные форматы и парные композиции. Размер новой работы выбирается из стандартного списка или задается индивидуально.\n\n## Условия\nДоставка оплачивается Заказчиком отдельно и не входит в стоимость картины. Маршрут и срок согласуются до отправки.",
     "body_en": "## Panoramic formats\nPanoramic formats and paired compositions are offered for long walls. The size of a new work is chosen from the standard list or set individually.",
     "seo_title_ru": "Картины в Волгограде", "seo_title_en": "Paintings in Volgograd",
     "seo_description_ru": "Картины в Волгограде: панорамные форматы, парные композиции, индивидуальные размеры. Доставка через СДЭК или другую ТК по согласованию."},
    {"source_id": "498677", "name_ru": "Саратов", "name_en": "Saratov", "name_in_ru": "в Саратове", "to": "в Саратов",
     "title_ru": "Картины в Саратове", "title_en": "Paintings in Saratov",
     "intro_ru": "Готовые картины и индивидуальные заказы с доставкой в Саратов.",
     "intro_en": "Ready paintings and custom commissions delivered to Saratov.",
     "body_ru": "## Городские и речные сюжеты\nВ каталоге есть городские виды и пейзажи с водой. По заявке возможна работа по вашему сюжету или фотографии места.\n\n## Заказ по фотографии\nПри заказе по фотографии уточняются формат, степень детализации и цветовое решение. Параметры согласуются до начала работы.",
     "body_en": "## City and river subjects\nThe catalogue includes city views and water landscapes. On request, a work based on your subject or photo is possible.",
     "seo_title_ru": "Картины в Саратове", "seo_title_en": "Paintings in Saratov",
     "seo_description_ru": "Картины в Саратове: городские и речные сюжеты, заказ по фотографии. Доставка через СДЭК или другую ТК, оплата доставки отдельно."},
    {"source_id": "1488754", "name_ru": "Тюмень", "name_en": "Tyumen", "name_in_ru": "в Тюмени", "to": "в Тюмень",
     "title_ru": "Картины в Тюмени", "title_en": "Paintings in Tyumen",
     "intro_ru": "Каталог картин и индивидуальные заказы для интерьеров Тюмени.",
     "intro_en": "Painting catalogue and custom commissions for interiors in Tyumen.",
     "body_ru": "## Для новых квартир\nКартина для нового интерьера подбирается с учетом отделки, мебели и освещения. Фото помещения в заявке помогает точнее определить формат и цветовое решение.\n\n## Сертификат\nВ качестве подарка доступен подарочный сертификат: номинал и формат выбираются в форме заявки.",
     "body_en": "## For new flats\nA painting for a new interior is chosen with the finish, furniture and lighting in mind. A photo of the room helps define format and colour.",
     "seo_title_ru": "Картины в Тюмени", "seo_title_en": "Paintings in Tyumen",
     "seo_description_ru": "Картины в Тюмени для новых квартир: подбор формата и цвета, индивидуальные заказы, подарочные сертификаты. Доставка через СДЭК или другую ТК."},
]


from seed.typical_cities import typical_cities  # noqa: E402

CITIES += typical_cities("d")
