"""Стартовые отзывы (комплект заказчика). Фото — кадры из утвержденного листа; даты демонстрационные: случайные за последние 3 года, для каждого сайта свои."""

REVIEWS = [
    {"author_ru": 'Екатерина', "author_en": 'Ekaterina', "city_ru": 'Москва', "city_en": 'Moscow',
     "text_ru": 'Работа подобрана для кабинета руководителя. Картина смотрится сдержанно, дорого и не перегружает пространство. Получили именно тот визуальный баланс, который хотели: статусно, но без избыточной декоративности.',
     "text_en": 'The work was chosen for an executive office. The painting looks restrained, expensive and does not overload the space. We got exactly the visual balance we wanted: prestigious, but without excessive decoration.',
     "date": "2024-06-20", "photo": "holstori_review_01.jpg", "painting_note": 'Цветы в холодной гамме', "featured": True},
    {"author_ru": 'Алексей', "author_en": 'Alexey', "city_ru": 'Санкт-Петербург', "city_en": 'Saint Petersburg',
     "text_ru": 'Нужен был крупный акцент для переговорной зоны. Картина хорошо держит стену, поддерживает современный интерьер и визуально собирает композицию помещения. Вживую фактура выглядит убедительнее, чем на карточке.',
     "text_en": 'We needed a large accent for the meeting area. The painting holds the wall well, supports the modern interior and visually pulls the composition of the room together. In person the texture looks more convincing than on the product page.',
     "date": "2024-03-20", "photo": "holstori_review_02.jpg", "painting_note": 'Абстракция, бежево-графитовая палитра'},
    {"author_ru": 'Михаил', "author_en": 'Mikhail', "city_ru": 'Калининград', "city_en": 'Kaliningrad',
     "text_ru": 'Выбрали работу для загородного дома. Понравилось сочетание силы сюжета и спокойной палитры. Картина заметная, но не кричащая — именно то, что требуется для интерьера с натуральными материалами.',
     "text_en": 'We chose the work for a country house. I liked the combination of a strong subject and a calm palette. The painting is noticeable but not loud — just what an interior with natural materials needs.',
     "date": "2025-01-23", "photo": "holstori_review_03.jpg", "painting_note": 'Морской пейзаж'},
    {"author_ru": 'Ольга', "author_en": 'Olga', "city_ru": 'Нижний Новгород', "city_en": 'Nizhny Novgorod',
     "text_ru": 'Картина размещена в столовой зоне. Тёплые акценты и тёмный фон создают выразительный, но дисциплинированный образ. Хороший пример того, как небольшая работа способна качественно изменить восприятие помещения.',
     "text_en": 'The painting is placed in the dining area. Warm accents and a dark background create an expressive yet disciplined image. A good example of how a small work can noticeably change the perception of a room.',
     "date": "2026-03-06", "photo": "holstori_review_04.jpg", "painting_note": 'Натюрморт с лимонами'},
    {"author_ru": 'Виктория', "author_en": 'Viktoria', "city_ru": 'Самара', "city_en": 'Samara',
     "text_ru": 'Заказывали для семейной гостиной. Работа гармонично вписалась в интерьер и стала одной из ключевых точек внимания. Отдельно отмечу корректную коммуникацию и аккуратную доставку.',
     "text_en": 'We ordered it for a family living room. The work fits harmoniously into the interior and has become one of its key focal points. I would also note the correct communication and careful delivery.',
     "date": "2025-01-10", "photo": "holstori_review_05.jpg", "painting_note": 'Пейзаж с домом'},
    {"author_ru": 'Игорь', "author_en": 'Igor', "city_ru": 'Новосибирск', "city_en": 'Novosibirsk',
     "text_ru": 'Портрет смотрится очень достойно: выразительно, современно, без ощущения плакатности. Использовали в частной библиотеке, где нужен был сильный, но интеллигентный акцент. Результат полностью соответствует ожиданиям.',
     "text_en": 'The portrait looks very dignified: expressive, modern, without a poster-like feel. We used it in a private library that needed a strong but refined accent. The result fully meets expectations.',
     "date": "2026-04-02", "photo": "holstori_review_06.jpg", "painting_note": 'Женский портрет'},
    {"author_ru": 'Марина', "author_en": 'Marina', "city_ru": 'Краснодар', "city_en": 'Krasnodar',
     "text_ru": 'Для прихожей искали лаконичную работу с графическим характером. Этот вариант оказался удачным: минималистично, чисто, уместно в современном интерьере. Упаковка и состояние при получении — без замечаний.',
     "text_en": 'For the hallway we were looking for a laconic work with a graphic character. This option turned out well: minimalist, clean, appropriate in a modern interior. Packaging and condition on receipt — no complaints.',
     "date": "2024-01-28", "photo": "holstori_review_07.jpg", "painting_note": 'Графичная ботаника'},
    {"author_ru": 'Сергей', "author_en": 'Sergey', "city_ru": 'Екатеринбург', "city_en": 'Yekaterinburg',
     "text_ru": 'Картина расположена в холле загородного дома. Сильный образ, спокойная палитра и хорошая работа со светом. Полотно добавило интерьеру глубины и статуса.',
     "text_en": 'The painting hangs in the hall of a country house. A strong image, a calm palette and good work with light. The canvas added depth and status to the interior.',
     "date": "2023-11-27", "photo": "holstori_review_08.jpg", "painting_note": 'Портрет лошади'},
    {"author_ru": 'Роман и Инна', "author_en": 'Roman and Inna', "city_ru": 'Воронеж', "city_en": 'Voronezh',
     "text_ru": 'Выбирали работу в подарок на новоселье. Картина смотрится элегантно и универсально, легко вошла в интерьер. Получатели остались очень довольны — это был безопасный и одновременно эффектный выбор.',
     "text_en": 'We were choosing a work as a housewarming gift. The painting looks elegant and versatile and fitted easily into the interior. The recipients were very pleased — it was a safe and at the same time impressive choice.',
     "date": "2025-02-28", "photo": "holstori_review_09.jpg", "painting_note": 'Городской вечерний сюжет'},
    {"author_ru": 'Людмила', "author_en": 'Lyudmila', "city_ru": 'Пермь', "city_en": 'Perm',
     "text_ru": 'Работа стала акцентом в спокойной светлой комнате. Нравится, что картина не спорит с интерьером, а добавляет ему структуру и характер. Визуально решение получилось очень собранным.',
     "text_en": 'The work became an accent in a calm, light room. I like that the painting does not argue with the interior but adds structure and character to it. Visually the solution turned out very cohesive.',
     "date": "2025-12-26", "photo": "holstori_review_10.jpg", "painting_note": 'Фигура в чёрном'},
]
