# Generated by Django 5.2.17 on 2026-09-29 11:24

import core.i18n
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=80, verbose_name="Название (RU)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Техника",
                "verbose_name_plural": "Техники",
                "ordering": ["order", "name_ru"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_ru",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=500,
                        verbose_name="Адрес RU",
                    ),
                ),
                (
                    "path_en",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=500,
                        verbose_name="Адрес EN",
                    ),
                ),
                (
                    "seo_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Смысловая часть после «Бренд |». Пусто — значение по шаблону типа страницы.",
                        max_length=200,
                        verbose_name="SEO Title (RU)",
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SEO Title (EN)"
                    ),
                ),
                (
                    "seo_description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Поддерживается вставка {brand}.",
                        verbose_name="Description (RU)",
                    ),
                ),
                (
                    "seo_description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
                (
                    "og_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Open Graph: заголовок (RU)",
                    ),
                ),
                (
                    "og_title_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Open Graph: заголовок (EN)",
                    ),
                ),
                (
                    "og_description_ru",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Open Graph: описание (RU)",
                    ),
                ),
                (
                    "og_description_en",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Open Graph: описание (EN)",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        upload_to="og/",
                        verbose_name="Open Graph: изображение",
                    ),
                ),
                (
                    "indexable",
                    models.BooleanField(
                        default=True,
                        help_text="Если выключено — noindex и исключение из sitemap.xml.",
                        verbose_name="Показывать в поиске",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=120, verbose_name="Название (RU)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — рубрики нет в английской версии.",
                        max_length=120,
                        verbose_name="Название (EN)",
                    ),
                ),
                (
                    "slug_ru",
                    models.CharField(
                        blank=True,
                        help_text="Кириллица, например «пейзажи».",
                        max_length=120,
                        verbose_name="ЧПУ (RU)",
                    ),
                ),
                (
                    "slug_en",
                    models.CharField(
                        blank=True,
                        help_text="Латиница, например «landscapes».",
                        max_length=120,
                        verbose_name="ЧПУ (EN)",
                    ),
                ),
                (
                    "intro_ru",
                    models.TextField(blank=True, verbose_name="Вводный текст (RU)"),
                ),
                (
                    "intro_en",
                    models.TextField(blank=True, verbose_name="Вводный текст (EN)"),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="categories/", verbose_name="Обложка"
                    ),
                ),
                (
                    "cover_alt_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt обложки (RU)"
                    ),
                ),
                (
                    "cover_alt_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt обложки (EN)"
                    ),
                ),
                (
                    "focus_x",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Фокус обложки по горизонтали, %",
                    ),
                ),
                (
                    "focus_y",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Фокус обложки по вертикали, %",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="Родительская рубрика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рубрика",
                "verbose_name_plural": "Рубрики каталога",
                "ordering": ["order", "name_ru"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Painting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_ru",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=500,
                        verbose_name="Адрес RU",
                    ),
                ),
                (
                    "path_en",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=500,
                        verbose_name="Адрес EN",
                    ),
                ),
                (
                    "seo_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Смысловая часть после «Бренд |». Пусто — значение по шаблону типа страницы.",
                        max_length=200,
                        verbose_name="SEO Title (RU)",
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SEO Title (EN)"
                    ),
                ),
                (
                    "seo_description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Поддерживается вставка {brand}.",
                        verbose_name="Description (RU)",
                    ),
                ),
                (
                    "seo_description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
                (
                    "og_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Open Graph: заголовок (RU)",
                    ),
                ),
                (
                    "og_title_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Open Graph: заголовок (EN)",
                    ),
                ),
                (
                    "og_description_ru",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Open Graph: описание (RU)",
                    ),
                ),
                (
                    "og_description_en",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Open Graph: описание (EN)",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        upload_to="og/",
                        verbose_name="Open Graph: изображение",
                    ),
                ),
                (
                    "indexable",
                    models.BooleanField(
                        default=True,
                        help_text="Если выключено — noindex и исключение из sitemap.xml.",
                        verbose_name="Показывать в поиске",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Название (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — картины нет в английской версии.",
                        max_length=200,
                        verbose_name="Название (EN)",
                    ),
                ),
                (
                    "slug_ru",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="ЧПУ (RU)"
                    ),
                ),
                (
                    "slug_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="ЧПУ (EN)"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="Артикул / локальный номер",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "В наличии"),
                            ("custom", "Под заказ"),
                            ("sold", "Продана"),
                        ],
                        default="custom",
                        max_length=12,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "author_ru",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Автор (RU)"
                    ),
                ),
                (
                    "author_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Автор (EN)"
                    ),
                ),
                (
                    "base_ru",
                    models.CharField(
                        blank=True,
                        help_text="Например: холст на подрамнике.",
                        max_length=120,
                        verbose_name="Основа (RU)",
                    ),
                ),
                (
                    "base_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Основа (EN)"
                    ),
                ),
                (
                    "framing_ru",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Оформление / рама (RU)",
                    ),
                ),
                (
                    "framing_en",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Оформление / рама (EN)",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                        verbose_name="Фактическая ширина, см",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                        verbose_name="Фактическая высота, см",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Пусто — показывается «Стоимость по запросу».",
                        max_digits=10,
                        null=True,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "short_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Короткое описание для карточки (RU)",
                    ),
                ),
                (
                    "short_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Короткое описание для карточки (EN)",
                    ),
                ),
                (
                    "description_mode",
                    models.CharField(
                        choices=[
                            ("template", "Общий текст описания"),
                            ("own", "Индивидуальное описание"),
                        ],
                        default="template",
                        max_length=10,
                        verbose_name="Источник описания",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, verbose_name="Индивидуальное описание (RU)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, verbose_name="Индивидуальное описание (EN)"
                    ),
                ),
                (
                    "sizes_mode",
                    models.CharField(
                        choices=[("common", "Общий список"), ("own", "Свои размеры")],
                        default="common",
                        max_length=10,
                        verbose_name="Желаемые размеры новой картины",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paintings",
                        to="catalog.category",
                        verbose_name="Рубрика",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.technique",
                        verbose_name="Техника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картина",
                "verbose_name_plural": "Картины",
                "ordering": ["order", "-created_at"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PaintingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="paintings/", verbose_name="Изображение"
                    ),
                ),
                (
                    "alt_ru",
                    models.CharField(
                        blank=True,
                        help_text="Описание того, что на изображении, без набора ключевых слов.",
                        max_length=255,
                        verbose_name="Alt (RU)",
                    ),
                ),
                (
                    "alt_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt (EN)"
                    ),
                ),
                (
                    "caption_ru",
                    models.CharField(
                        blank=True,
                        help_text="Например: деталь, в интерьере.",
                        max_length=120,
                        verbose_name="Подпись (RU)",
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Подпись (EN)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "painting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.painting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение картины",
                "verbose_name_plural": "Изображения (первое — основное)",
                "ordering": ["order", "id"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PaintingSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                        verbose_name="Ширина, см",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                        verbose_name="Высота, см",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "painting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_sizes",
                        to="catalog.painting",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.standardsize",
                        verbose_name="Стандартный формат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Свой размер",
                "verbose_name_plural": "Свои размеры (при режиме «Свои размеры»)",
                "ordering": ["order", "id"],
            },
        ),
    ]
