# Generated by Django 5.2.17 on 2026-09-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="canonical_override",
            field=models.CharField(
                blank=True,
                help_text="Обычно пусто: canonical формируется автоматически. Указывайте адрес основной версии только для дублей, например /каталог/море/.",
                max_length=500,
                verbose_name="Canonical вручную",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="caption_en",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Подпись под плиткой (EN)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="caption_ru",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Подпись под плиткой (RU)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="cta_button_en",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Блок заказа внизу: кнопка (EN)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="cta_button_ru",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Блок заказа внизу: кнопка (RU)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="cta_text_en",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Блок заказа внизу: текст (EN)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="cta_text_ru",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Блок заказа внизу: текст (RU)"
            ),
        ),
        migrations.AddField(
            model_name="painting",
            name="canonical_override",
            field=models.CharField(
                blank=True,
                help_text="Обычно пусто: canonical формируется автоматически. Указывайте адрес основной версии только для дублей, например /каталог/море/.",
                max_length=500,
                verbose_name="Canonical вручную",
            ),
        ),
    ]
