# Generated by Django 5.2.17 on 2026-09-29 11:24

import core.i18n
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="GeoNames", max_length=40, verbose_name="Источник"
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                        verbose_name="ID в источнике",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        db_index=True, max_length=2, verbose_name="Код страны"
                    ),
                ),
                ("country_ru", models.CharField(max_length=80, verbose_name="Страна")),
                (
                    "country_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Страна (EN)"
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=120, verbose_name="Регион"),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True, max_length=120, verbose_name="Название"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "name_source",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название в источнике"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=5, max_digits=9, verbose_name="Широта"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=5, max_digits=9, verbose_name="Долгота"
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Население"
                    ),
                ),
                (
                    "population_date",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Дата статистики"
                    ),
                ),
                (
                    "is_capital",
                    models.BooleanField(default=False, verbose_name="Столица"),
                ),
                (
                    "is_admin_center",
                    models.BooleanField(
                        default=False, verbose_name="Административный центр региона"
                    ),
                ),
                (
                    "loaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "manually_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Обновление справочника не перезаписывает такие записи.",
                        verbose_name="Изменено вручную",
                    ),
                ),
                (
                    "sale_confirmed",
                    models.BooleanField(
                        default=False, verbose_name="Продажа подтверждена"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=False, verbose_name="Показывать отметку на карте"
                    ),
                ),
                (
                    "caption_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись (RU)"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись (EN)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "География продаж — города",
                "ordering": ["country_ru", "name_ru"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("source_id", ""), _negated=True),
                        fields=("source", "source_id"),
                        name="city_unique_source",
                    )
                ],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
    ]
