# Generated by Django 5.2.17 on 2026-09-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="name_ru_verified",
            field=models.BooleanField(
                default=False,
                help_text="Да — взято из языковых альтернатив GeoNames (ru) или проверено вручную.",
                verbose_name="Русское название подтверждено",
            ),
        ),
    ]
