# Generated by Django 5.2.17 on 2026-09-29 11:24

import django.core.files.storage
import django.db.models.deletion
import importapi.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, verbose_name="Название подключения"
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        editable=False,
                        max_length=16,
                        unique=True,
                        verbose_name="Идентификатор",
                    ),
                ),
                ("secret_hash", models.CharField(editable=False, max_length=64)),
                (
                    "can_upload",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        verbose_name="Загрузка фотографий в рубрики",
                    ),
                ),
                (
                    "can_replace_cover",
                    models.BooleanField(
                        default=False, verbose_name="Замена обложки рубрики"
                    ),
                ),
                (
                    "can_create_cards",
                    models.BooleanField(
                        default=False,
                        verbose_name="Создание карточек-черновиков из фото",
                    ),
                ),
                (
                    "can_publish",
                    models.BooleanField(
                        default=False, verbose_name="Публикация созданных карточек"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее использование"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Отозван"),
                ),
            ],
            options={
                "verbose_name": "API-ключ",
                "verbose_name_plural": "API импорта — ключи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время"
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(blank=True, max_length=16, verbose_name="Ключ"),
                ),
                ("action", models.CharField(max_length=40, verbose_name="Действие")),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Внешний ID"
                    ),
                ),
                (
                    "category_id_value",
                    models.CharField(blank=True, max_length=40, verbose_name="Рубрика"),
                ),
                (
                    "file_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Файл"),
                ),
                ("result", models.CharField(max_length=20, verbose_name="Результат")),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Сообщение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись журнала импорта",
                "verbose_name_plural": "API импорта — журнал",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=200, verbose_name="Внешний идентификатор"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("photo", "Фотография работы"),
                            ("cover", "Обложка рубрики"),
                        ],
                        default="photo",
                        max_length=10,
                        verbose_name="Назначение",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("accepted", "Принят, ждет назначения"),
                            ("assigned", "Назначен карточке"),
                            ("draft_created", "Создана карточка-черновик"),
                            ("published", "Создана и опубликована карточка"),
                            ("cover_set", "Установлен как обложка"),
                        ],
                        default="accepted",
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url=None,
                            location=pathlib.PurePosixPath(
                                "/home/user/art/var/a/private"
                            ),
                        ),
                        upload_to=importapi.models.import_path,
                        verbose_name="Обработанный файл",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя файла"
                    ),
                ),
                (
                    "sha256",
                    models.CharField(max_length=64, verbose_name="Контрольная сумма"),
                ),
                (
                    "width",
                    models.PositiveIntegerField(default=0, verbose_name="Ширина, px"),
                ),
                (
                    "height",
                    models.PositiveIntegerField(default=0, verbose_name="Высота, px"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Принят"),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="importapi.apikey",
                        verbose_name="Ключ",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.category",
                        verbose_name="Рубрика",
                    ),
                ),
                (
                    "painting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.painting",
                        verbose_name="Картина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл импорта",
                "verbose_name_plural": "API импорта — принятые файлы",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("external_id",), name="import_unique_external_id"
                    )
                ],
            },
        ),
    ]
