# Generated by Django 5.2.17 on 2026-09-29 11:24

import core.i18n
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateNominal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Номинал")),
                (
                    "label_ru",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Подпись (RU)"
                    ),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Подпись (EN)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
            ],
            options={
                "verbose_name": "Номинал сертификата",
                "verbose_name_plural": "Номиналы сертификата",
                "ordering": ["order", "amount"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_ru",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=500,
                        verbose_name="Адрес RU",
                    ),
                ),
                (
                    "path_en",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=500,
                        verbose_name="Адрес EN",
                    ),
                ),
                (
                    "seo_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Смысловая часть после «Бренд |». Пусто — значение по шаблону типа страницы.",
                        max_length=200,
                        verbose_name="SEO Title (RU)",
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SEO Title (EN)"
                    ),
                ),
                (
                    "seo_description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Поддерживается вставка {brand}.",
                        verbose_name="Description (RU)",
                    ),
                ),
                (
                    "seo_description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
                (
                    "og_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Open Graph: заголовок (RU)",
                    ),
                ),
                (
                    "og_title_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Open Graph: заголовок (EN)",
                    ),
                ),
                (
                    "og_description_ru",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Open Graph: описание (RU)",
                    ),
                ),
                (
                    "og_description_en",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Open Graph: описание (EN)",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        upload_to="og/",
                        verbose_name="Open Graph: изображение",
                    ),
                ),
                (
                    "indexable",
                    models.BooleanField(
                        default=True,
                        help_text="Если выключено — noindex и исключение из sitemap.xml.",
                        verbose_name="Показывать в поиске",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("home", "Главная"),
                            ("about", "О нас"),
                            ("studio", "О студии"),
                            ("catalog", "Каталог"),
                            ("reviews", "Отзывы"),
                            ("delivery", "Доставка"),
                            ("contacts", "Контакты"),
                            ("sold", "Проданные картины / SOLD"),
                            ("certificate", "Подарочный сертификат"),
                            ("custom", "Картины на заказ"),
                            ("guides", "Полезное (список статей)"),
                            ("text", "Текстовая страница"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Тип страницы",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Заголовок H1 (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — у страницы нет английской версии.",
                        max_length=200,
                        verbose_name="Заголовок H1 (EN)",
                    ),
                ),
                (
                    "nav_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Для меню и хлебных крошек.",
                        max_length=80,
                        verbose_name="Короткое название (RU)",
                    ),
                ),
                (
                    "nav_title_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Короткое название (EN)"
                    ),
                ),
                (
                    "slug_ru",
                    models.CharField(
                        blank=True,
                        help_text="Кириллица, например «о-нас». Для главной — пусто.",
                        max_length=120,
                        verbose_name="ЧПУ (RU)",
                    ),
                ),
                (
                    "slug_en",
                    models.CharField(
                        blank=True,
                        help_text="Латиница, например «about». Адрес будет /en/about/.",
                        max_length=120,
                        verbose_name="ЧПУ (EN)",
                    ),
                ),
                (
                    "intro_ru",
                    models.TextField(
                        blank=True, verbose_name="Вводный текст / анонс (RU)"
                    ),
                ),
                (
                    "intro_en",
                    models.TextField(
                        blank=True, verbose_name="Вводный текст / анонс (EN)"
                    ),
                ),
                (
                    "body_ru",
                    models.TextField(
                        blank=True,
                        help_text="Абзацы — через пустую строку. «## Подзаголовок», «- пункт», **жирный**, [ссылка](/адрес/), {brand} — название сайта.",
                        verbose_name="Основной текст (RU)",
                    ),
                ),
                (
                    "body_en",
                    models.TextField(blank=True, verbose_name="Основной текст (EN)"),
                ),
                (
                    "note_ru",
                    models.TextField(
                        blank=True,
                        help_text="Выделенный блок условий, подпись под картой и т.п.",
                        verbose_name="Дополнительный блок (RU)",
                    ),
                ),
                (
                    "note_en",
                    models.TextField(
                        blank=True, verbose_name="Дополнительный блок (EN)"
                    ),
                ),
                (
                    "empty_ru",
                    models.TextField(
                        blank=True, verbose_name="Текст пустого состояния (RU)"
                    ),
                ),
                (
                    "empty_en",
                    models.TextField(
                        blank=True, verbose_name="Текст пустого состояния (EN)"
                    ),
                ),
                (
                    "button_ru",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Кнопка (RU)"
                    ),
                ),
                (
                    "button_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Кнопка (EN)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="pages/",
                        verbose_name="Изображение страницы",
                    ),
                ),
                (
                    "image_alt_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt изображения (RU)"
                    ),
                ),
                (
                    "image_alt_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt изображения (EN)"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        upload_to="banners/",
                        verbose_name="Баннер: изображение для компьютера",
                    ),
                ),
                (
                    "banner_image_mobile",
                    models.ImageField(
                        blank=True,
                        upload_to="banners/",
                        verbose_name="Баннер: изображение для телефона",
                    ),
                ),
                (
                    "banner_focus_x",
                    models.PositiveSmallIntegerField(
                        default=50, verbose_name="Баннер: фокус по горизонтали, %"
                    ),
                ),
                (
                    "banner_focus_y",
                    models.PositiveSmallIntegerField(
                        default=50, verbose_name="Баннер: фокус по вертикали, %"
                    ),
                ),
                (
                    "banner_kicker_ru",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Баннер: надпись над заголовком (RU)",
                    ),
                ),
                (
                    "banner_kicker_en",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Баннер: надпись над заголовком (EN)",
                    ),
                ),
                (
                    "banner_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Баннер: заголовок (RU)",
                    ),
                ),
                (
                    "banner_title_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Баннер: заголовок (EN)",
                    ),
                ),
                (
                    "banner_text_ru",
                    models.TextField(blank=True, verbose_name="Баннер: текст (RU)"),
                ),
                (
                    "banner_text_en",
                    models.TextField(blank=True, verbose_name="Баннер: текст (EN)"),
                ),
                (
                    "banner_button1_ru",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Баннер: кнопка 1 (RU)"
                    ),
                ),
                (
                    "banner_button1_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Баннер: кнопка 1 (EN)"
                    ),
                ),
                (
                    "banner_button1_link",
                    models.CharField(
                        blank=True,
                        help_text="Например, «catalog» — ссылка на каталог; или адрес /…/.",
                        max_length=255,
                        verbose_name="Баннер: ссылка кнопки 1",
                    ),
                ),
                (
                    "banner_button2_ru",
                    models.CharField(
                        blank=True,
                        help_text="Открывает форму заказа.",
                        max_length=80,
                        verbose_name="Баннер: кнопка 2 (RU)",
                    ),
                ),
                (
                    "banner_button2_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Баннер: кнопка 2 (EN)"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
                "ordering": ["order", "id"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StudioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="studio/", verbose_name="Изображение"),
                ),
                (
                    "alt_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt (RU)"
                    ),
                ),
                (
                    "alt_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt (EN)"
                    ),
                ),
                (
                    "caption_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись (RU)"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись (EN)"
                    ),
                ),
                (
                    "is_illustration",
                    models.BooleanField(
                        default=True,
                        help_text="Для сгенерированных изображений: рядом выводится нейтральная пометка, что это иллюстрация.",
                        verbose_name="Иллюстрация, а не фотография реального помещения",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
            ],
            options={
                "verbose_name": "Изображение студии",
                "verbose_name_plural": "О студии — изображения",
                "ordering": ["order", "id"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_ru",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=500,
                        verbose_name="Адрес RU",
                    ),
                ),
                (
                    "path_en",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=500,
                        verbose_name="Адрес EN",
                    ),
                ),
                (
                    "seo_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Смысловая часть после «Бренд |». Пусто — значение по шаблону типа страницы.",
                        max_length=200,
                        verbose_name="SEO Title (RU)",
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SEO Title (EN)"
                    ),
                ),
                (
                    "seo_description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Поддерживается вставка {brand}.",
                        verbose_name="Description (RU)",
                    ),
                ),
                (
                    "seo_description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
                (
                    "og_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Open Graph: заголовок (RU)",
                    ),
                ),
                (
                    "og_title_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Open Graph: заголовок (EN)",
                    ),
                ),
                (
                    "og_description_ru",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Open Graph: описание (RU)",
                    ),
                ),
                (
                    "og_description_en",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Open Graph: описание (EN)",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        upload_to="og/",
                        verbose_name="Open Graph: изображение",
                    ),
                ),
                (
                    "indexable",
                    models.BooleanField(
                        default=True,
                        help_text="Если выключено — noindex и исключение из sitemap.xml.",
                        verbose_name="Показывать в поиске",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Заголовок H1 (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок H1 (EN)"
                    ),
                ),
                (
                    "slug_ru",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="ЧПУ (RU)"
                    ),
                ),
                (
                    "slug_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="ЧПУ (EN)"
                    ),
                ),
                ("excerpt_ru", models.TextField(blank=True, verbose_name="Анонс (RU)")),
                ("excerpt_en", models.TextField(blank=True, verbose_name="Анонс (EN)")),
                (
                    "body_ru",
                    models.TextField(
                        blank=True,
                        help_text="Абзацы — через пустую строку. «## Подзаголовок», «- пункт», **жирный**, [ссылка](/адрес/).",
                        verbose_name="Текст (RU)",
                    ),
                ),
                ("body_en", models.TextField(blank=True, verbose_name="Текст (EN)")),
                (
                    "button_ru",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Кнопка (RU)"
                    ),
                ),
                (
                    "button_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Кнопка (EN)"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="articles/", verbose_name="Обложка"
                    ),
                ),
                (
                    "cover_alt_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt обложки (RU)"
                    ),
                ),
                (
                    "cover_alt_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt обложки (EN)"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "related_categories",
                    models.ManyToManyField(
                        blank=True,
                        to="catalog.category",
                        verbose_name="Связанные рубрики",
                    ),
                ),
                (
                    "related_paintings",
                    models.ManyToManyField(
                        blank=True,
                        to="catalog.painting",
                        verbose_name="Связанные картины",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Полезное — статьи",
                "ordering": ["order", "-published_at", "id"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HomeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("intro", "Вводный блок"),
                            ("categories", "Рубрики каталога"),
                            ("available", "В наличии"),
                            ("custom", "Картины под заказ"),
                            ("sold", "Проданные работы"),
                            ("order", "Индивидуальный заказ"),
                            ("reviews", "Отзывы"),
                            ("delivery", "Доставка"),
                            ("guides", "Полезное"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Блок",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок (RU)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок (EN)"
                    ),
                ),
                ("text_ru", models.TextField(blank=True, verbose_name="Текст (RU)")),
                ("text_en", models.TextField(blank=True, verbose_name="Текст (EN)")),
                (
                    "button_ru",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Кнопка (RU)"
                    ),
                ),
                (
                    "button_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Кнопка (EN)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="home/", verbose_name="Изображение блока"
                    ),
                ),
                (
                    "limit",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="Сколько работ показывать"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "paintings",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Пусто — последние опубликованные работы с подходящим статусом.",
                        to="catalog.painting",
                        verbose_name="Работы для показа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок главной",
                "verbose_name_plural": "Главная — блоки",
                "ordering": ["order", "id"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_ru",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — короткое название выбранной страницы.",
                        max_length=60,
                        verbose_name="Надпись (RU)",
                    ),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Надпись (EN)"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Или своя ссылка"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
                (
                    "in_footer",
                    models.BooleanField(
                        default=True, verbose_name="Повторять в футере"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.page",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Меню",
                "ordering": ["order", "id"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_ru", models.TextField(verbose_name="Текст отзыва (RU)")),
                (
                    "text_en",
                    models.TextField(blank=True, verbose_name="Текст отзыва (EN)"),
                ),
                (
                    "author_ru",
                    models.CharField(
                        max_length=120, verbose_name="Имя или подпись (RU)"
                    ),
                ),
                (
                    "author_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Имя или подпись (EN)"
                    ),
                ),
                (
                    "city_ru",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Город (RU)"
                    ),
                ),
                (
                    "city_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Город (EN)"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="reviews/", verbose_name="Фото"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "painting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.painting",
                        verbose_name="Картина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["order", "-created_at"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
    ]
