# Generated by Django 5.2.17 on 2026-09-29 15:03

import core.i18n
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="library/", verbose_name="Изображение"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=160, verbose_name="Название в медиатеке"
                    ),
                ),
                (
                    "alt_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt (RU)"
                    ),
                ),
                (
                    "alt_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt (EN)"
                    ),
                ),
                (
                    "caption_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подпись (RU)"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подпись (EN)"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
            ],
            options={
                "verbose_name": "Изображение медиатеки",
                "verbose_name_plural": "Медиатека",
                "ordering": ["-uploaded_at"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.AddField(
            model_name="article",
            name="canonical_override",
            field=models.CharField(
                blank=True,
                help_text="Обычно пусто: canonical формируется автоматически. Указывайте адрес основной версии только для дублей, например /каталог/море/.",
                max_length=500,
                verbose_name="Canonical вручную",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="canonical_override",
            field=models.CharField(
                blank=True,
                help_text="Обычно пусто: canonical формируется автоматически. Указывайте адрес основной версии только для дублей, например /каталог/море/.",
                max_length=500,
                verbose_name="Canonical вручную",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="cta_button_en",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Блок заказа внизу: кнопка (EN)"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="cta_button_ru",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Блок заказа внизу: кнопка (RU)"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="cta_text_en",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Блок заказа внизу: текст (EN)"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="cta_text_ru",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Блок заказа внизу: текст (RU)"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="kicker_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Надпись над заголовком (EN)"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="kicker_ru",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Надпись над заголовком (RU)"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата отзыва"),
        ),
        migrations.AddField(
            model_name="review",
            name="featured",
            field=models.BooleanField(
                default=False, verbose_name="Крупно в начале страницы"
            ),
        ),
    ]
