# Generated by Django 5.2.17 on 2026-09-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_mediaasset_article_canonical_override_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homesection",
            name="kicker_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Надпись над заголовком (EN)"
            ),
        ),
        migrations.AddField(
            model_name="homesection",
            name="kicker_ru",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Надпись над заголовком (RU)"
            ),
        ),
    ]
