# Generated by Django 5.2.17 on 2026-09-29 16:25

import core.i18n
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_homesection_kicker"),
        ("geo", "0002_city_name_ru_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="kind",
            field=models.CharField(
                choices=[
                    ("home", "Главная"),
                    ("about", "О нас"),
                    ("studio", "О студии"),
                    ("catalog", "Каталог"),
                    ("reviews", "Отзывы"),
                    ("delivery", "Доставка"),
                    ("contacts", "Контакты"),
                    ("sold", "Проданные картины / SOLD"),
                    ("certificate", "Подарочный сертификат"),
                    ("custom", "Картины на заказ"),
                    ("guides", "Полезное (список статей)"),
                    ("cities", "Города (список городских страниц)"),
                    ("text", "Текстовая страница"),
                ],
                default="text",
                max_length=20,
                verbose_name="Тип страницы",
            ),
        ),
        migrations.CreateModel(
            name="CityLanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_ru",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=500,
                        verbose_name="Адрес RU",
                    ),
                ),
                (
                    "path_en",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=500,
                        verbose_name="Адрес EN",
                    ),
                ),
                (
                    "seo_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Смысловая часть после «Бренд |». Пусто — значение по шаблону типа страницы.",
                        max_length=200,
                        verbose_name="SEO Title (RU)",
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SEO Title (EN)"
                    ),
                ),
                (
                    "seo_description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Поддерживается вставка {brand}.",
                        verbose_name="Description (RU)",
                    ),
                ),
                (
                    "seo_description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
                (
                    "og_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Open Graph: заголовок (RU)",
                    ),
                ),
                (
                    "og_title_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Open Graph: заголовок (EN)",
                    ),
                ),
                (
                    "og_description_ru",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Open Graph: описание (RU)",
                    ),
                ),
                (
                    "og_description_en",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Open Graph: описание (EN)",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        upload_to="og/",
                        verbose_name="Open Graph: изображение",
                    ),
                ),
                (
                    "indexable",
                    models.BooleanField(
                        default=True,
                        help_text="Если выключено — noindex и исключение из sitemap.xml.",
                        verbose_name="Показывать в поиске",
                    ),
                ),
                (
                    "canonical_override",
                    models.CharField(
                        blank=True,
                        help_text="Обычно пусто: canonical формируется автоматически. Указывайте адрес основной версии только для дублей, например /каталог/море/.",
                        max_length=500,
                        verbose_name="Canonical вручную",
                    ),
                ),
                ("name_ru", models.CharField(max_length=80, verbose_name="Город (RU)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Город (EN)"
                    ),
                ),
                (
                    "name_in_ru",
                    models.CharField(
                        blank=True,
                        help_text="Например: «в Москве», «в Казани».",
                        max_length=100,
                        verbose_name="«в городе» (RU)",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Заголовок H1 (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок H1 (EN)"
                    ),
                ),
                (
                    "slug_ru",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="ЧПУ (RU)"
                    ),
                ),
                (
                    "slug_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="ЧПУ (EN)"
                    ),
                ),
                (
                    "intro_ru",
                    models.TextField(blank=True, verbose_name="Вступление (RU)"),
                ),
                (
                    "intro_en",
                    models.TextField(blank=True, verbose_name="Вступление (EN)"),
                ),
                (
                    "body_ru",
                    models.TextField(
                        blank=True,
                        help_text="Свой текст для этого города. «## Подзаголовок», «- пункт», **жирный**, [ссылка](/адрес/).",
                        verbose_name="Текст страницы (RU)",
                    ),
                ),
                (
                    "body_en",
                    models.TextField(blank=True, verbose_name="Текст страницы (EN)"),
                ),
                (
                    "delivery_ru",
                    models.TextField(
                        blank=True,
                        help_text="Как получить картину в этом городе. Только реальные условия.",
                        verbose_name="Доставка и получение в городе (RU)",
                    ),
                ),
                (
                    "delivery_en",
                    models.TextField(
                        blank=True, verbose_name="Доставка и получение в городе (EN)"
                    ),
                ),
                (
                    "address_ru",
                    models.CharField(
                        blank=True,
                        help_text="Реальный адрес. Пусто — блок адреса и карта не выводятся.",
                        max_length=255,
                        verbose_name="Адрес (RU)",
                    ),
                ),
                (
                    "address_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Адрес (EN)"
                    ),
                ),
                (
                    "address_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "address_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "hours_ru",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Режим работы (RU)"
                    ),
                ),
                (
                    "hours_en",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Режим работы (EN)"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — используется общий телефон сайта.",
                        max_length=40,
                        verbose_name="Телефон в городе",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="cities/", verbose_name="Изображение"
                    ),
                ),
                (
                    "cover_alt_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt изображения (RU)"
                    ),
                ),
                (
                    "cover_alt_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt изображения (EN)"
                    ),
                ),
                (
                    "button_ru",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Кнопка (RU)"
                    ),
                ),
                (
                    "button_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Кнопка (EN)"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="Связь с картой продаж: в подсказке карты появится ссылка на эту страницу.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.city",
                        verbose_name="Город из справочника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Городская страница",
                "verbose_name_plural": "Города — страницы",
                "ordering": ["order", "name_ru"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
    ]
