# Generated by Django 5.2.17 on 2026-10-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_city_landing"),
    ]

    operations = [
        migrations.AddField(
            model_name="citylanding",
            name="geo_aliases",
            field=models.TextField(
                blank=True,
                help_text="Необязательно. По одному на строку: как геобаза может назвать этот город (например, «Yekaterinburg»). Только явные правила, догадок «соседний город ≈ этот» нет.",
                verbose_name="Названия для автоопределения",
            ),
        ),
        migrations.AddField(
            model_name="citylanding",
            name="show_in_picker",
            field=models.BooleanField(
                default=True,
                help_text="Список «Выбрать другой» на городских страницах для посетителей из РФ.",
                verbose_name="Показывать в выборе города",
            ),
        ),
    ]
