# Generated by Django 5.2.17 on 2026-10-01 04:47

import content.coop_icons
import core.i18n
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_city_geo_picker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="kind",
            field=models.CharField(
                choices=[
                    ("home", "Главная"),
                    ("about", "О нас"),
                    ("studio", "О студии"),
                    ("catalog", "Каталог"),
                    ("reviews", "Отзывы"),
                    ("delivery", "Доставка"),
                    ("contacts", "Контакты"),
                    ("sold", "Проданные картины / SOLD"),
                    ("certificate", "Подарочный сертификат"),
                    ("custom", "Картины на заказ"),
                    ("cooperation", "Сотрудничество"),
                    ("guides", "Полезное (список статей)"),
                    ("cities", "Города (список городских страниц)"),
                    ("text", "Текстовая страница"),
                ],
                default="text",
                max_length=20,
                verbose_name="Тип страницы",
            ),
        ),
        migrations.CreateModel(
            name="CooperationContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_mode",
                    models.CharField(
                        choices=[
                            ("brand", "1. Фирменный фон по утверждённому дизайну"),
                            ("photo_full", "2. Фото на весь фон"),
                            (
                                "split",
                                "3. Фото справа + текстовый блок (по утверждённому макету)",
                            ),
                            ("none", "4. Без изображения"),
                        ],
                        default="split",
                        help_text="Если выбран режим с фото, а фото нет или оно скрыто — показывается фирменный фон дизайна.",
                        max_length=12,
                        verbose_name="Тип фона",
                    ),
                ),
                (
                    "hero_kicker_ru",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Надзаголовок (RU)"
                    ),
                ),
                (
                    "hero_kicker_en",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Надзаголовок (EN)"
                    ),
                ),
                (
                    "h1_ru",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — берётся заголовок страницы.",
                        max_length=200,
                        verbose_name="Заголовок H1 (RU)",
                    ),
                ),
                (
                    "h1_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок H1 (EN)"
                    ),
                ),
                (
                    "hero_subtitle_ru",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Подзаголовок (RU)"
                    ),
                ),
                (
                    "hero_subtitle_en",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Подзаголовок (EN)"
                    ),
                ),
                (
                    "hero_lead_ru",
                    models.TextField(
                        blank=True, verbose_name="Абзац под подзаголовком (RU)"
                    ),
                ),
                (
                    "hero_lead_en",
                    models.TextField(
                        blank=True, verbose_name="Абзац под подзаголовком (EN)"
                    ),
                ),
                (
                    "hero_button_ru",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — кнопка не показывается.",
                        max_length=80,
                        verbose_name="Кнопка постера (RU)",
                    ),
                ),
                (
                    "hero_button_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Кнопка постера (EN)"
                    ),
                ),
                (
                    "hero_button_action",
                    models.CharField(
                        choices=[
                            ("form", "Открыть общую форму заявки"),
                            ("url", "Перейти по ссылке"),
                        ],
                        default="form",
                        max_length=8,
                        verbose_name="Действие кнопки постера",
                    ),
                ),
                (
                    "hero_button_url",
                    models.CharField(
                        blank=True,
                        help_text="Для действия «Перейти по ссылке»: /адрес/ или https://…",
                        max_length=255,
                        verbose_name="Ссылка кнопки постера",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        upload_to="cooperation/",
                        verbose_name="Фото постера (для компьютера)",
                    ),
                ),
                (
                    "hero_image_mobile",
                    models.ImageField(
                        blank=True,
                        help_text="Нет — используется то же фото с учётом точки фокуса.",
                        upload_to="cooperation/",
                        verbose_name="Фото постера для телефона (необязательно)",
                    ),
                ),
                (
                    "hero_image_alt_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ALT фото (RU)"
                    ),
                ),
                (
                    "hero_image_alt_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ALT фото (EN)"
                    ),
                ),
                (
                    "hero_show_image",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть фото, не удаляя его.",
                        verbose_name="Показывать фото постера",
                    ),
                ),
                (
                    "hero_focus_x",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Точка фокуса по горизонтали, %",
                    ),
                ),
                (
                    "hero_focus_y",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Точка фокуса по вертикали, %",
                    ),
                ),
                (
                    "hero_overlay",
                    models.SmallIntegerField(
                        default=35,
                        help_text="Только для режима «Фото на весь фон»: от −80 (осветлить) до 80 (затемнить).",
                        validators=[
                            django.core.validators.MinValueValidator(-80),
                            django.core.validators.MaxValueValidator(80),
                        ],
                        verbose_name="Затемнение (+) / осветление (−) для текста, %",
                    ),
                ),
                (
                    "cta_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Финальный блок: заголовок (RU)",
                    ),
                ),
                (
                    "cta_title_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Финальный блок: заголовок (EN)",
                    ),
                ),
                (
                    "cta_text_ru",
                    models.TextField(
                        blank=True, verbose_name="Финальный блок: текст (RU)"
                    ),
                ),
                (
                    "cta_text_en",
                    models.TextField(
                        blank=True, verbose_name="Финальный блок: текст (EN)"
                    ),
                ),
                (
                    "cta_button_ru",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Финальный блок: кнопка (RU)",
                    ),
                ),
                (
                    "cta_button_en",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Финальный блок: кнопка (EN)",
                    ),
                ),
                (
                    "cta_button_action",
                    models.CharField(
                        choices=[
                            ("form", "Открыть общую форму заявки"),
                            ("url", "Перейти по ссылке"),
                        ],
                        default="form",
                        max_length=8,
                        verbose_name="Финальный блок: действие кнопки",
                    ),
                ),
                (
                    "cta_button_url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Финальный блок: ссылка кнопки",
                    ),
                ),
                (
                    "cta_image",
                    models.ImageField(
                        blank=True,
                        upload_to="cooperation/",
                        verbose_name="Финальный блок: изображение",
                    ),
                ),
                (
                    "cta_image_alt_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Финальный блок: ALT (RU)",
                    ),
                ),
                (
                    "cta_image_alt_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Финальный блок: ALT (EN)",
                    ),
                ),
                (
                    "cta_show_image",
                    models.BooleanField(
                        default=True, verbose_name="Показывать изображение"
                    ),
                ),
                (
                    "cta_focus_x",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Фокус по горизонтали, %",
                    ),
                ),
                (
                    "cta_focus_y",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Фокус по вертикали, %",
                    ),
                ),
                (
                    "adv_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Заголовок блока преимуществ (RU)",
                    ),
                ),
                (
                    "adv_title_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Заголовок блока преимуществ (EN)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "cta_image_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.mediaasset",
                        verbose_name="…или изображение из медиатеки",
                    ),
                ),
                (
                    "hero_image_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.mediaasset",
                        verbose_name="…или фото из медиатеки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница «Сотрудничество»",
                "verbose_name_plural": "Страница «Сотрудничество»",
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CooperationBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="Показывать блок"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок (RU)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок (EN)"
                    ),
                ),
                ("text_ru", models.TextField(blank=True, verbose_name="Текст (RU)")),
                ("text_en", models.TextField(blank=True, verbose_name="Текст (EN)")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="cooperation/", verbose_name="Изображение"
                    ),
                ),
                (
                    "alt_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ALT (RU)"
                    ),
                ),
                (
                    "alt_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ALT (EN)"
                    ),
                ),
                (
                    "show_image",
                    models.BooleanField(
                        default=True, verbose_name="Показывать изображение"
                    ),
                ),
                (
                    "image_side",
                    models.CharField(
                        choices=[
                            ("right", "Фото справа / текст слева"),
                            ("left", "Фото слева / текст справа"),
                        ],
                        default="right",
                        max_length=5,
                        verbose_name="Положение изображения",
                    ),
                ),
                (
                    "focus_x",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Фокус по горизонтали, %",
                    ),
                ),
                (
                    "focus_y",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Фокус по вертикали, %",
                    ),
                ),
                (
                    "image_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.mediaasset",
                        verbose_name="…или из медиатеки",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="content.cooperationcontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок «текст + фото»",
                "verbose_name_plural": "Блоки «текст + фото»",
                "ordering": ["order", "id"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CooperationAdvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("individual", "Человек — индивидуальный подход"),
                            ("flexible", "Палитра — гибкие решения"),
                            ("brief", "Планшет с отметкой — работа по ТЗ"),
                            ("delivery", "Грузовик — доставка"),
                            ("longterm", "Сердце — долгосрочное сотрудничество"),
                            ("frame", "Рамка с картиной"),
                            ("ruler", "Линейка — размеры"),
                            ("chat", "Диалог — обсуждение"),
                            ("clock", "Часы — сроки"),
                            ("shield", "Щит с галочкой — надёжность"),
                            ("globe", "Глобус — география"),
                            ("package", "Коробка — упаковка"),
                        ],
                        help_text="Пусто — без пиктограммы (пустой рамки не будет).",
                        max_length=24,
                        verbose_name="Пиктограмма из набора",
                    ),
                ),
                (
                    "icon_file",
                    models.FileField(
                        blank=True,
                        help_text="Загруженный файл заменяет пиктограмму из набора. До 300 КБ.",
                        upload_to="cooperation/icons/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["svg", "png", "webp"]
                            ),
                            content.coop_icons.validate_icon_file,
                        ],
                        verbose_name="…или своя пиктограмма (SVG/PNG)",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название (RU)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "text_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Короткое описание (RU)",
                    ),
                ),
                (
                    "text_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Короткое описание (EN)",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantages",
                        to="content.cooperationcontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
                "ordering": ["order", "id"],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
    ]
