# Generated by Django 5.2.17 on 2026-10-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_cooperation_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cooperationadvantage",
            name="icon_key",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual", "Человек — индивидуальный подход"),
                    ("flexible", "Карандаш с плюсом — гибкие решения"),
                    ("brief", "Планшет с отметкой — работа по ТЗ"),
                    ("delivery", "Грузовик — доставка"),
                    ("partner", "Связь — партнёрство и долгосрочное сотрудничество"),
                    (
                        "longterm",
                        "Сердце — долгосрочное сотрудничество (прежний вариант)",
                    ),
                    ("frame", "Рамка с картиной"),
                    ("ruler", "Линейка — размеры"),
                    ("chat", "Диалог — обсуждение"),
                    ("clock", "Часы — сроки"),
                    ("shield", "Щит с галочкой — надёжность"),
                    ("globe", "Глобус — география"),
                    ("package", "Коробка — упаковка"),
                ],
                help_text="Пусто — без пиктограммы (пустой рамки не будет).",
                max_length=24,
                verbose_name="Пиктограмма из набора",
            ),
        ),
        migrations.AlterField(
            model_name="cooperationcontent",
            name="hero_mode",
            field=models.CharField(
                choices=[
                    ("brand", "A) Фирменный фон по текущему дизайну"),
                    ("split", "B) Фото в правой части, как на эталоне"),
                    ("photo_full", "C) Фото на весь фон"),
                    ("none", "D) Без изображения"),
                ],
                default="split",
                help_text="Если выбран режим с фото, а фото нет или оно скрыто — показывается фирменный фон дизайна. По умолчанию — B, как на эталоне.",
                max_length=12,
                verbose_name="Тип фона",
            ),
        ),
    ]
